### ISSUE TITLE
crush when keep scrolling at high speed [bug]

### ISSUE THREAD

**Issue by MeetBall73** [noah-nuebling/Mac-Mouse-Fix#1029]
## Description

as title

## Steps to reproduce

1. scroll
2. keep scrolling faster
3. crush

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: 14.4
Mouse Model: logitech vertical

## Additional Comments

–

---

### Console Logs

Failed to connect (disableScroll) outlet from (Mac_Mouse_Fix_Helper.MenuBarItem) to (NSMenuItem): missing setter or instance variable

### Crash Reports

https://pastebin.com/zZPV2XpD

**Comment by MeetBall73** [comment]
update:
 not just high speed, even if I scroll multiple times at normal slow speed, it crushed.

**Comment by windblower420** [comment]
I can experience this as well. didnt happen in the old version. just updated right now and when I scroll super fast it takes me to another window. I use the same middle button for switching desktops on press and swipe. 

maybe for now allow us to deactivate mechanism for scrolling until its fixed?

**Comment by noah-nuebling** [comment]
Hey guys, thanks for the reports! 

This should be fixed in the latest [3.0.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.3). 

If anybody is still experiencing these crashes (or if you did still experience them when you were last using 3.0.2) it would be really valuable if you sent your config.plist file so I can have a look at it.

The config.plist file holds pretty much all settings and state that is retained between launches of the app. You can find it like this:

1. Open Mac Mouse Fix
2. Go to the 'About' tab
3. Click the Mac Mouse Fix Icon while holding Command (⌘) and Shift (⇧). This should reveal the 'config.plist' file in the Finder.

I'm closing this Issue now, so everything related to this bug is in one place. For further discussion and details, please use Issue [#988](https://github.com/noah-nuebling/mac-mouse-fix/issues/988#issuecomment-2359171135). Thank you.
