### ISSUE TITLE
Mac Mouse Fix suddenly stops working [bug]

### ISSUE THREAD

**Issue by adityaastro** [noah-nuebling/Mac-Mouse-Fix#1037]
## Description

Mac Mouse Fix suddenly stops working intermittently every few minutes and it takes about 5 - 10s for it to kick back in. It is very annoying and wastes a lot of time for me

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: Sonoma 14.5
Mouse Model: Logitech MX Master 3S

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by ImmerTry** [comment]
I also encountered it！
----------------------------------------
Mac Mouse Fix Version: 3.0.2（22635）
macOS Version: Sonoma 14.4 (23E214)
Mouse Model: Logitech G304/G102

**Comment by adityaastro** [comment]
Any updates @noah-nuebling?

**Comment by jaekyeom** [comment]
I believe this is due to crashing, which I'm experiencing frequently as well if I enable scrolling smoothness.

**Comment by noah-nuebling** [comment]
Hey there guys, thank you for the reports, and sorry for the late reply.

This should be fixed in the latest [3.0.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.3). 

If anybody is still experiencing these crashes (or if you did still experience them when you were last using 3.0.2) it would be really valuable if you sent your config.plist file so I can have a look at it.

The config.plist file holds pretty much all settings and state that is retained between launches of the app. You can find it like this:

1. Open Mac Mouse Fix
2. Go to the 'About' tab
3. Click the Mac Mouse Fix Icon while holding Command (⌘) and Shift (⇧). This should reveal the 'config.plist' file in the Finder.

I'm closing this Issue now, so everything related to this bug is in one place. For further discussion and details, please use Issue [#988](https://github.com/noah-nuebling/mac-mouse-fix/issues/988#issuecomment-2359171135). Thank you.
