### ISSUE TITLE
Keeps restarting randomly [bug]

### ISSUE THREAD

**Issue by h4ckt1v1st** [noah-nuebling/Mac-Mouse-Fix#1040]
## Description

The app quickly goes offline for a couple of seconds, I can see the icon disappears from the menu bar and then it comes back after 2-3 seconds. I noticed this usually while scrolling because the scroll direction changes suddenly.

## Steps to reproduce

1. Usually notice this when I am doing a lot of quick scrolling. But it also happens sometimes without doing any scrolling.

## Context

Mac Mouse Fix Version: 2.2.4
macOS Version: Sonoma 14.5
Mouse Model: Dell Compact Wireless Keyboard and Mouse Set KM7120W

## Additional Comments

This has started to happen recently like I have been noticing this for a couple of weeks.

---

### Console Logs

–

### Crash Reports

–

**Comment by adityaastro** [comment]
Facing the exact same issue and causes me a lot of problems.

**Comment by noah-nuebling** [comment]
Hey there, thanks for the report! And I'm sorry for the late reply.

This should be fixed in the latest [3.0.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.3). 

If you guys are still experiencing these crashes (or if you did still experience them when you were last using 3.0.2) it would be really valuable if you sent your config.plist file so I can have a look at it.

The config.plist file holds pretty much all settings and state that is retained between launches of the app. You can find it like this:

1. Open Mac Mouse Fix
2. Go to the 'About' tab
3. Click the Mac Mouse Fix Icon while holding Command (⌘) and Shift (⇧). This should reveal the 'config.plist' file in the Finder.

I'm closing this Issue now, so everything related to this bug is in one place. For further discussion and details, please use Issue [#988](https://github.com/noah-nuebling/mac-mouse-fix/issues/988#issuecomment-2359171135). Thank you.
