### ISSUE TITLE
Crashes! [bug]

### ISSUE THREAD

**Issue by ercanert** [noah-nuebling/Mac-Mouse-Fix#1048]
## Description

I'm able to use it with no problem for some time. Then it starts to crash and open itself back immediately. The issue goes away when I restart the computer. I also used Smooze Pro for some time together with it, but I disabled it, still have the same issue. I was using Blender when I encountered this issue.  My mouse has two extra buttons and I use them to navigate in Blender and my computer.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.4
macOS Version: 11.6.7
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

https://pastebin.com/8KKciF7q

**Comment by noah-nuebling** [comment]
Hey there, thank you for the bug report.

This should be fixed in the latest [3.0.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.3). 

If you're still experiencing these crashes (or if you did still experience them when you were last using 3.0.2) it would be really valuable if you sent your config.plist file so I can have a look at it.

The config.plist file holds pretty much all settings and state that is retained between launches of the app. You can find it like this:

1. Open Mac Mouse Fix
2. Go to the 'About' tab
3. Click the Mac Mouse Fix Icon while holding Command (⌘) and Shift (⇧). This should reveal the 'config.plist' file in the Finder.

I'm closing this Issue now, so everything related to this bug is in one place. For further discussion and details, please use Issue [#988](https://github.com/noah-nuebling/mac-mouse-fix/issues/988#issuecomment-2359171135). Thank you.
