### ISSUE TITLE
Disable invert scrolling for trackpad

### ISSUE THREAD

**Issue by marchein** [noah-nuebling/mac-mouse-fix#12]
I love to use the "natural scrolling" on my trackpad of my Macbook, but I like to have it "normal" on my mouse if I am at my desk. 

So would it be possible to just use the inverted scrolling for actual mice?

**Comment by noah-nuebling** [comment]
Hi marchein, Mac Mouse Fix shouldn't change anything about the behavior of your trackpad. The "Invert direction" option should only change the scrolling direction of your Mouse.
Would you mind telling me what kind of trackpad you are using, and which version of macOS you are running? Thanks!

**Comment by marchein** [comment]
But it does. I am using a 2018 15" MacBook Pro running the current Catalina GM.

**Comment by noah-nuebling** [comment]
Are you using any other software to modify scrolling behavior?

**Comment by marchein** [comment]
No. Just your app.

**Comment by noah-nuebling** [comment]
Are you 100% sure that your issue is caused by Mac Mouse Fix? If the scrolling algorithm doesn't ignore your trackpad, that should totally break your trackpad scrolling. I just tested this and on my 2015 MBP 13', and it makes the trackpad scrolling feel really weird and it constantly gets stuck for a few seconds at a time.

**Comment by marchein** [comment]
Reinstalled Catalina. Seems like something from the past messed with the settings and conflicted. Works fine now. Closing the issue.

**Comment by noah-nuebling** [comment]
Okay, thank you for reaching out!
