### ISSUE TITLE
Safari Tab Scrolling [enhancement]

### ISSUE THREAD

**Issue by c-fisc24** [noah-nuebling/mac-mouse-fix#122]
## Description
Scrolling through the stack of (many) opened tabs with the scrollwheel (in safari), it seems to work when mac mouse fix is turned off, but not when its enabled. 

## Rationale
it would allow me to keep the navigation of the tabs flowing! 

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi, @c-fisc24, thanks for the feedback!

You should be able to hold Shift (⇧) to scroll the tab bar in Safari (and anything else) horizontally.
I plan on providing easier ways to scroll horizontally without touching your keyboard in the future, but I can't give you a concrete timeframe for that, so please don't hold your breath.

---

**Explanation**

The problem here is that, Safari seems to only translate vertical scrolling on the tab bar to horizontal scrolling automatically, _if_ it thinks the input device is a normal mouse with a scroll wheel. When you use a trackpad, it won't do that.

Since Mac Mouse Fix makes your mouse send smooth scrolling events, I guess that makes Safari think "Oh these events are smooth - this must be a trackpad - so there's no need to scroll horizontally automatically"

**Comment by noah-nuebling** [comment]
Hey @c-fisc24, you can now scroll horizontally in the Safari tab bar and elsewhere using just one hand in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

You can scroll horizontally using either "Click and Scroll" or "Click and Drag".

I hope you like it!

Let me know if you have more thoughts or issues! And please open a new issue if the current solution in MMF 3 isn't optimal for you. 

Thanks!
