### ISSUE TITLE
Smooth Scrolling in the App Store on Big Sur 11.4 is choppy sometimes. [bug]

### ISSUE THREAD

**Issue by ghost** [noah-nuebling/mac-mouse-fix#127]
## Description

The scrolling animation in the App Store suddenly becomes very choppy and laggy when Mac Mouse Fix is enabled.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 1.0.4
macOS Version: 11.4
Mouse Model: XiaoMi Dual Mode Wireless Mouse Silent Edition

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @JuNkY14257, 

thanks for the heads up, I wasn't aware of this.

I'm not sure I can do much about this in the near future, but here's my understanding of the issue, if you're interested:

The apps running on macOS normally expect scroll events to either be 
a. smooth and gesture-based and produced by a Magic Mouse or Magic Trackpad, which will also send information about the swipe gesture causing the scrolling, or
b. Be simple and non-smooth and produced by a scroll wheel on a normal mouse.

Now, Mac Mouse Fix sends events that are hybrid between those two types of events. They are smooth but they don't contain any of this gesture information, that scroll events from an Apple device would.

This works fine with most apps, but some of them behave weirdly due to these slightly unexpected scroll events. Ranging from stuttering in the App Store to scrolling incredibly fast in Preview.

Eventually, I'd like to have Mac Mouse Fix simulate the way that a Magic Trackpad sends events super closely, so that all apps will behave as expected. But that requires me to dig into the bits and bytes of these events and figure out exactly how the Apple scroll events work under the hood and then replicate that. 

I already did that for three finger swipes to enable the Click and Drag for Mission Control and Spaces feature in 2.0.0, but doing the same for gesture scrolls proved a lot more difficult. I'm working on it though. This would be really neat and solve many little problems.

**Until then, you can turn off smooth scrolling for the App Store under "More... → App-specific settings..."** to hopefully make it behave better for you.

**Comment by noah-nuebling** [comment]
Hey @JuNkY14257, pleased to inform you that scrolling in the app store should now work just as well as with a trackpad in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)! 

That's because MMF 3 now closely emulates the scroll events that Apples Trackpad driver outputs.

Let me know if you have more thoughts or issues!
