### ISSUE TITLE
Middle Button functions on Logitech M275 not working in High Sierra 10.13.6 [other]

### ISSUE THREAD

**Issue by AbishekRufusRaj** [noah-nuebling/mac-mouse-fix#131]
I set the click function of the middle button to show desktop..it does not do the function (i.e. show desktop)..and similar issues to all other middle button function..

**Comment by noah-nuebling** [comment]
Hey @AbishekRufusRaj, thanks for reaching out!

Does the “Invert direction” option work for you? (It should invert the direction that websites and other content scroll when you move the scroll wheel in a certain direction)

If the “Invert direction” option doesn’t work for you, then the problem is likely with Enabling Mac Mouse Fix.
If the option does work then the issue would seem to be with how Mac Mouse Fix interacts with your mouse. Which is kind of weird because I have the Logitech M720 and it works just fine. I’d recon they communicate with the computer in very similar ways.

**Comment by AbishekRufusRaj** [comment]
Thank you for checking back with me..like this did not work in the mac-mouse-fix2 beta 11 (2.0.0)..Just to make sure we're on the same page..

The "invert direction" **does** work in the Mac Mouse Fix 2 beta 11...but the other function like "click to show desktop" or others..does not work..Not sure if the issue is with my mouse though..is there anything I should do?

The app is very helpful btw!

**Comment by noah-nuebling** [comment]
Hmm that’s really weird.
I’m not sure what’s going on then, could be a number of things.

If you have time we can investigate the issue further.
But of course I can’t promise that we’ll solve the issue very soon.

First thing you could test is whether your Middle Button works. To test that you could:

1. Disable Mac Mouse Fix
2. Open Safari and click a link with the Middle Mouse Button

The link should then open in a new tab if your Middle Mouse Button works.

**Comment by noah-nuebling** [comment]
Oh and thanks for letting me know that the app is helpful to you, that’s nice to hear :)

**Comment by AbishekRufusRaj** [comment]
> Hmm that’s really weird.
> I’m not sure what’s going on then, could be a number of things.
> 
> If you have time we can investigate the issue further.
> But of course I can’t promise that we’ll solve the issue very soon.
> 
> First thing you could test is whether your Middle Button works. To test that you could:
> 
> 1. Disable Mac Mouse Fix
> 2. Open Safari and click a link with the Middle Mouse Button
> 
> The link should then open in a new tab if your Middle Mouse Button works.
I guess the middle button is the issue...I tried with another mouse..it works fine!
Thanks again!!!

**Comment by noah-nuebling** [comment]
Okay great, glad that’s cleared up :)
