### ISSUE TITLE
Horizontal scroll with shift

### ISSUE THREAD

**Issue by Cristian-farinella** [noah-nuebling/mac-mouse-fix#147]
### Discussed in https://github.com/noah-nuebling/mac-mouse-fix/discussions/146

<div type='discussions-op-text'>

<sup>Originally posted by **Cristian-farinella** July 23, 2021</sup>
Am I the only one who horizontal scroll doesn't work? Before opening a bug report, I wanted to be sure. Shift and wheel by default on Mac OS horizontally scrolls, but it seems it doesn't work with smooth scrolling opened by Mouse-fix.</div>

**Comment by noah-nuebling** [comment]
Hey Christian thanks for your report!

Mac Mouse Fix does have a feature that should allow you to scroll horizontally while holding shift. Regarding your problem I think there are 3 possibilities:

1. Some other background software on your computer is interfering with scrolling or with the shift key.
2. Maybe you’ve turned off Horizontal Scrolling under App-specific settings in MMF
3. There’s a bug in MMF causing this.

I actually think I remember having this issue myself, too at some point, so I think it’s probably a very rare bug. But since I plan on rewriting the scrolling system and the modifier system as my next goal, I don’t think it makes sense to focus too much energy on this bug right now. (Because it has a good chance of going away with the rewrite anyways.)

For me, I think the issue went away after disabling and then re-enabling MMF or after re-installing MMF. Does that help in your case? 

Hope that helps or at least clears things up. If you have anymore questions or issues let me know.

**Comment by noah-nuebling** [comment]
Hey @Cristian-farinella

You can now test the new, rewritten scrolling system in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases). Hopefully it will fix your issues!

Please file a new Bug Report if you continue to have problems. Thanks!
