### ISSUE TITLE
Unable to drag through multiple spaces [bug]

### ISSUE THREAD

**Issue by chamburr** [noah-nuebling/mac-mouse-fix#150]
## Description

With the click and drag feature for switching spaces, I am unable to drag through multiple spaces.

Example: https://chamburr.xyz/u/S7rDpK.mp4

## Steps to reproduce

1. Create 3 spaces.
2. Try to drag from space 1 to 3.
3. Notice it jumps back to space 2.

## Context

Mac Mouse Fix Version: 2.0.0 Beta 12
macOS Version: 11.4 (20F71)
Mouse Model: –

## Additional Comments

–

**Comment by noah-nuebling** [comment]
@chamburr Hey Han, thanks for your feedback. This is unfortunately a restriction on the side of macOS and I don't know that there is much that Mac Mouse Fix can do to fix this. That's because MMF is essentially just simulating trackpad input to realize the "Mission Control & Spaces" feature.

But, with several small flicks you should find it easy to comfortably traverse several spaces anyways.

If you have anymore questions or suggestions let me know.

**Comment by chamburr** [comment]
@noah-nuebling Hi Noah, thank you for explaining. I see the case now.

I do have several other suggestions, hopefully this doesn't come across as overwhelming:
- A click and scroll gesture to zoom/horizontally scroll, it would be much easier without holding a key.
- A separate setting on scroll speed for zooming, as I find zooming too fast under my settings.

Let me know if they are feasible, and if I should open separate issues for them.

Also, thanks for making this app! I really appreciate the simplicity it brings.

**Comment by noah-nuebling** [comment]
They are totally feasible! I've been working on almost exactly the improvements you've requested. But I can't give you a timeframe on when they might release unfortunately because these features do take a lot of work and time to get right and I have lots of other things to do right now. But just know that I want these features at least as much as you do.

I'm glad you like the app! :)
