### ISSUE TITLE
Middle mouse button: Double click won't identify it [other]

### ISSUE THREAD

**Issue by hzx505** [noah-nuebling/Mac-Mouse-Fix#160]
Middle mouse button: Double click won't identify it, hold can identify.
Mouse model: Microsoft Wireless Mouse 5000 (one side button on each side, 5 keys in total)

Microsoft® 2.4GHz Transceiver v7.0：

Thanks for sharing technology to solve the problem of mouse smoothing！

note:
Version 2.0.0 Beta 12 (6195)
macOS 10.15.7

**Comment by noah-nuebling** [comment]
Hey @hzx505 thanks for your feedback! 

I don't know why this issue is happening. The only thing I can think of is that, on most mice, the scroll wheel click goes bad after a while and you have to press it quite hard to get it to activate.

If you want to dig deeper into this you could try to download the source code and debug it, or file a [Bug Report](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report).

**Comment by noah-nuebling** [comment]
I'll close this now, assuming the issue has been resolved for you. If you still have problems, just reopen this issue (or leave a comment telling me to reopen it if that's not possible)

Thanks!
