### ISSUE TITLE
Translating app into other languages [other]

### ISSUE THREAD

**Issue by rakleed** [noah-nuebling/Mac-Mouse-Fix#176]
Could you please provide the community with the ability to translate the app into other languages?

P.S. I can help with translation into Russian.

**Comment by Suma-xy** [comment]
I would help translating the App Into German

**Comment by noah-nuebling** [comment]
Hi guys, thanks for your feedback!

I've already put some work into a UI refresh that would allow for translating the app! But it's still a long ways off at this point.

One problem is that you need to write code to translate the app, I think. 
Specifically the text on the left side of the new Action Table.

<img width="543" alt="CleanShot 2022-01-05 at 11 49 22@2x" src="https://user-images.githubusercontent.com/40808343/148272148-4faca8e6-8341-4a66-8913-ee694cff0da1.png">

It's assembled in code from many little bits and pieces of information, and I think to translate it well with correct grammar etc, you _have_ to write a separate function for each language. You can't just do a simple string replacement like you usually do to translate apps.

Maybe I can do the function in some more beginner friendly programming language like Python? 
If you guys have any ideas how to make this easier for you to translate, let me know.

Edit: I probably wrote it in a bad way but the code for generating those trigger strings is currently 165 lines!!

**Comment by rakleed** [comment]
@noah-nuebling 

> Specifically the text on the left side of the new Action Table.
> 
> ![image](https://user-images.githubusercontent.com/19418601/148571057-bc320d98-d97a-4ccb-96d7-9f5eed3631b9.png)
> 
> It's assembled in code from many little bits and pieces of information, and I think to translate it well with correct grammar etc, you have to write a separate function for each language. You can't just do a simple string replacement like you usually do to translate apps.

I mentally went through several different options, and never once ran into a problem where it would not be possible to translate correctly by simply replacing the lines (at least into Russian).

**Comment by noah-nuebling** [comment]
I also speak German and for example “Triple Click and Hold Button 4” should become “Taste 4 Dreifach Klicken und Halten”

But if you simply replace the two substring “Triple Click and Hold” and “Button 4” with their German counterparts it would become “Dreifach Klicken und Halten Taste 4” which sounds grammatically wrong.

Also it goes even deeper because we don’t use “Single Click and Hold Button 4” we just shorten it to “Hold Button 4” for better readability. And when you have a Click and Drag Gesture we don’t make it “Double Click and Hold and then Drag” we shorten it to “Double Click and Drag” so it sounds better.

The end result is that even the string “Double Click and Hold” is assembled from 2 or 3 substrings as things currently work.

I just feel like this would all be a confusing mess to translate by just replacing strings. And if the order of the substrings must change for it to make it grammatically correct in your language (which we found an example for in German), or if the grammatical case must change depending on context, that would be impossible using just Apple’s translation frameworks (which only lets you replace strings and pluralize) as far as I know.

So the only way to achieve proper translation is using a third party framework which is more flexible, or doing it in code.

Do you think that makes sense?

**Comment by noah-nuebling** [comment]
Here’s the code for generating the string:

https://github.com/noah-nuebling/mac-mouse-fix/blob/db73119760c43f382b2c740611bfc28540a5754a/App/RemapTable/RemapTableTranslator.m#L482

 I wrote it very sloppily without thinking about it much before, or abstracting it completely from the structure in the which the underlying data is stored. So it might be a little confusing. And it might be a bad approach for the problem.

Lmk if you have any questions or ideas!

**Comment by rakleed** [comment]
Now I understand the complexity, but I don't know which solution is best for this case.

**Comment by noah-nuebling** [comment]
Hey, I've thought about this some more and I do think it's feasibly to do by just replacing hardcoded strings if I restructure things a little and use format strings. Thanks for your input.

**Comment by wgdavies** [comment]
These are kind of generic, but the first link has a lot of great links for more information on the topic. 

https://developer.apple.com/localization/

https://www.accelingo.com/how-to-internationalize-software/

https://aso.app/en/how-to-internationalise-your-app-to-get-more-users/

**Comment by noah-nuebling** [comment]
Hey guys, the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases) can now be translated into other languages!

I'd be super excited to have the app available in more languages!

For more info see **[MMF 3 Beta 1 Release Notes](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-1.1) > 9. Internationalization**

Let me know if you have any thoughts or questions!
