### ISSUE TITLE
Version 0.9.1 Removed Look Up option in the hold Middle-Mouse Button settings

### ISSUE THREAD

**Issue by of-ravens-claw** [noah-nuebling/mac-mouse-fix#18]

**Comment by noah-nuebling** [comment]
Hi Victor, thank you for your feedback.

I removed that option in 0.9.1 because I thought there were some usability issues with it. I explained my reasoning in more detail [here](https://github.com/noah-nuebling/mac-mouse-fix/blob/master/CHANGELOG.md). Looking back, I'm not entirely sure whether that decision made sense.

If you want to, you can [download](https://drive.google.com/open?id=1RtDDEhfscs3aj0J7OD_tT3lpOifLKPb2) an early version of 0.9.2 where I added the option back in. It also features subtle improvements to the scrolling algorithm, and you can be the first to get your hands on them! :) 
This version is my daily driver and it should be stable.

**Comment by of-ravens-claw** [comment]
Alright, thanks
