### ISSUE TITLE
less smooth

### ISSUE THREAD

**Issue by azerafati** [noah-nuebling/mac-mouse-fix#19]
Love your work here, thanks.👍🏼
Only need a feature to let me control the amount of smooth scrolling. It's perfect but i believe it's too much for me or at least for my mouse, If I could make it **less smooth** it would be awesome.

**Comment by noah-nuebling** [comment]
Hey azerafati, thank you for your feedback and suggestion!

Unfortunately, I can’t promise you that I’ll ever implement this feature because I'm not sure how to implement it in a way that makes sense for Mac Mouse Fix, but I am taking it into consideration.

However, and I know this is not a great substitute, but there are a few scrolling parameters that can be changed by editing the configuration file of Mouse Fix Helper manually. Note that all the settings in the config file that you can't change from the Prefpane (Scroll Step Time and Friction Coefficient) will reset to their default value, whenever you change _any_ setting in the Prefpane. I want to change that in a future version of Mac Mouse Fix.

Anyways, to find the configuration file go to 

_(if you installled Mac Mouse Fix for 'this user')_
~/Library/PreferencePanes/Mouse Fix.prefPane/Contents/Library/LoginItems/Mouse Fix Helper.app/Contents/Resources/config.plist

_(or if you installed Mac Mouse Fix for 'all users')_
/Library/PreferencePanes/Mouse Fix.prefPane/Contents/Library/LoginItems/Mouse Fix Helper.app/Contents/Resources/config.plist

If you open the config.plist file with Xcode it should look something like this:

<img width="684" alt="Screenshot 2019-10-27 at 12 09 02" src="https://user-images.githubusercontent.com/40808343/67633720-ac982f80-f8b3-11e9-977d-6f8030e38412.png">

You can play around with the values marked in red to change scrolling behavior. The cursive text explains what each value is.

You should be able to make the scrolling feel less smooth by increasing the friction coefficient and decreasing the step time.

If you have any further questions or suggestions or if you find any configurations that you especially like feel free to let me know!

**Comment by noah-nuebling** [comment]
Scrolling in the newest version is much less smooth and more responsive now!
