### ISSUE TITLE
Feature Request: Click and Drag to Scroll [enhancement]

### ISSUE THREAD

**Issue by tmngtk** [noah-nuebling/Mac-Mouse-Fix#194]
## Description
Click mouse button  3 or 4 or 5 and drag to vertical   horizontal scroll

## Rationale
I am a trackball user. I'd like to scroll the screen in 2D by rotating the ball. I guess a mouse user only with a vertical wheel would hope this future, too.

## Additional info
Thank you for the great app!

**Comment by zacnoo** [comment]
I just came on here to see if anyone else wanted this. It's an amazing feature, even for normal mice, panning has always sucked with regular mice on macOS compared to a trackpad, but xy drag-scrolling while locking the cursor stationary pretty much replicates the functionality of native trackpads.

Currently I'm just using the 'Smart Scroll' app but it's buggy and uses janky calculations, but it works and at high refresh rate. I would love if Mac Mouse Fix had this as well, since the trackpad emulation is so amazing.

**Comment by noah-nuebling** [comment]
Hey guys thx for reaching out! I really want this feature as well, and I already put a lot of work into it in the version-3 branch. It's really hard to get right though. And I want to get it right. So please don't expect this to come any time soon.

**Comment by zacnoo** [comment]
It's honestly just awesome to know you're working on it. There are temporary solutions for now, so it's not the end of the world. I love your application by the way!

Since you're using trackpad emulation, would that mean that if this functionality were to be implemented that trackpad exclusive scrolling events like horizontal scrolling in Calendar.app would also work?

**Comment by noah-nuebling** [comment]
Thank you that's so nice to hear. :)

> Would that mean that if this functionality were to be implemented that trackpad exclusive scrolling events like horizontal scrolling in Calendar.app would also work?

Yes!! Also swiping between pages in Safari, marking mails as unread in Mail, etc. etc.

**Comment by zacnoo** [comment]
> Yes!! Also swiping between pages in Safari, marking mails as unread in Mail, etc. etc.

Wow that would be a game changer. You're doing some awesome work. I'm gonna donate but you should consider putting a price on it. It's totally unique and well polished, and is very performant.

Edit: I guess this is also a duplicate of #28?

**Comment by noah-nuebling** [comment]
Thanks for the feedback man, that's really motivating.

> Edit: I guess this is also a duplicate of #28?

Good catch.

**Comment by noah-nuebling** [comment]
Hey @zacnoo, Click and Drag to Scroll is finally here in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!!

**Comment by zacnoo** [comment]
> Hey @zacnoo, Click and Drag to Scroll is finally here in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!!

I've been playing around with it. Amazing work mate, just bought it. Never thought I'd be using native side scroll gestures with an external mouse. 

Game changer. I'm happy you're gonna be charging for your hard work, you've earned it.

(If I'm being picky it would be nice to have a "non-smoothed" toggle for the click and drag scroll, since trackballs kinda add their own physical inertia with the mechanism)

**Comment by noah-nuebling** [comment]
Thanks! I'm so glad you like it!



> If I'm being picky it would be nice to have a "non-smoothed" toggle for the click and drag scroll, since trackballs kinda add their own physical inertia with the mechanism

That's very interesting, I don't have a trackball mouse, so I didn't know they did had their own inertia! 

I definitely want to get a trackball mouse at some point and try to optimize for that.
