### ISSUE TITLE
Middle click function gone [other]

### ISSUE THREAD

**Issue by shoperfy** [noah-nuebling/Mac-Mouse-Fix#196]
On latest version (2.0 (6294)) the normal middle click function on mouse is gone. Im using a g pro wireless and when it was beta 12 or 13 the middle click would work fine when i tried in chrome to open a new tab. Even if i remove all functions from middle click it still wont budge.

**Comment by firatciftci** [comment]
I am also experiencing this issue and it is a major dealbreaker for me. I would like the option to have the default function of the middle click back (e.g., for Chrome, middle clicking a tab closes it, middle clicking a link opens it in a new tab, etc.).

**Comment by noah-nuebling** [comment]
Hey guys thanks for reaching out!

This is really strange. Beta 13 and 2.0.0 are almost the exact same. I just double checked and none of the changes seem to be related to Middle Clicking at all.
I also can't reproduce this issue.

Here are some things you could try:

1. Reset the config file to default.
Maybe the config file has been corrupted. You can reset it to default like this:

https://user-images.githubusercontent.com/40808343/148715158-c469d4f4-13dc-4b90-899e-bc1deac38141.mp4

2. Test Beta 13 again and let me know how it goes.
The original Beta 13 release is unusable now due to the signing issues, but I rebuilt it from the original source code and you can [download it here](https://github.com/noah-nuebling/mac-mouse-fix/files/7836674/MacMouseFixApp-2.0.0-Beta-13.zip).

3. File a bug report and attach some console logs.
That might give us more insight into what's going on.
Click [here](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report) to file a report.

**Comment by shoperfy** [comment]
It seems like the new update and also resetting the config file might've fixed it? Either way just putting middle click on click for the middle button restores the function so it works now. Thanks for the help :)
