### ISSUE TITLE
Scroll Gesture on Trackpad killed [bug]

### ISSUE THREAD

**Issue by fortysix2ahead** [noah-nuebling/Mac-Mouse-Fix#204]
## Description

I tried out MMF 2.0 (and also 2.1) and it killed the two finger scrolling gesture on the trackpad. All other gestures still work (like three finger Mission Control), clicks also work. But since the installation of MMF the scroll gesture is gone, which is pretty annoying and I don't know how to get it back working.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.1.0
macOS Version: Catalina
Mouse Model: Logitech MX Perfomance

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hmm that is very strange. 
Mac Mouse Fix does need to intercept your trackpad's scrolling, because macOS doesn't let you intercept mouse scrolls without intercepting trackpad scrolls as well, so there's some potential for issues here. But I don't think I changed the scrolling code between 1.0.0 and 2.1.0. and no one has ever reported any issues of this sort.

Here are some things you could try to help figure this out:

- Tell me what trackpad / computer you're using.
- Tell me if scrolling works again when you disable Mac Mouse Fix.
- Tell me if there are any other users logged in on your computer.
- File a bug report [here](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report) and attach some console logs of you scrolling on the trackpad.

Thanks for reaching out!

**Comment by fortysix2ahead** [comment]
I can't tell if MMF is really the problem. It could also be that this a coincidence. I only can tell that the scroll gesture stopped working around the time when I installed MMF. I can't tell exactly as I am usually using a separate mouse (Logitech MX Performance).
- The trackpad is the built-in on a Macbook Pro 15, mid 2015, running Catalina.
- No, disabling MMF does not help. Revoking the priviledges also does not work.
- No, only one user.
- Searched through the system console logs for 'mouse' or 'nuebling', but did not find anything suspicious - any idea where to search for useful information?

**Comment by fortysix2ahead** [comment]
Found the problem (see https://appuals.com/fix-trackpad-scroll-not-working-on-macos/). Go to System Preferences > Accessibility > Mouse & Trackpad > Trackpad Options. The check box 'Scrolling' was unticked. Ticking the option and set it to 'With Inertia' restores the ability to scroll. The only question that remains: which application did clear this setting as I am not aware of having ever seen this menu item. Don't know if MMF did that?

**Comment by noah-nuebling** [comment]
Cool, glad you could figure it out!

Let me know if you find out more about why that happened.

**Comment by noah-nuebling** [comment]
I'm not aware of anything in Mac Mouse Fix that might have caused this.

**Comment by fortysix2ahead** [comment]
So, it's only a coincidence. Let's see if I can find out who or what caused this setting.
