### ISSUE TITLE
Missing an option to disable the middle-button click & drag feature [other]

### ISSUE THREAD

**Issue by Floflo35** [noah-nuebling/Mac-Mouse-Fix#205]
Please add an option to disable the middle-button click & drag feature

It can be annoying in some apps, and there's no way to disable it

great app otherwise!

**Comment by amadav** [comment]
You can try selecting the option and then delete it.

![image](https://user-images.githubusercontent.com/9503440/148843433-9a221e06-fb0b-4df2-9c99-cda9eb0cdfb8.png)

**Comment by Floflo35** [comment]
Oh I didn't notice that, thanks a lot!

**Comment by noah-nuebling** [comment]
Glad you guys figured it out, I'll think about how to make that more obvious.

**Comment by dc-p8** [comment]
I was also looking for this, the UI doesn't make you think you can delete defaults shortcuts.

**Comment by noah-nuebling** [comment]
Reopened so other people with the same issue can find this more easily

**Comment by noah-nuebling** [comment]
@dc-p8 Thanks for chiming in. 

I added a right-click menu for deleting, do you guys think that would help?

<img width="500" alt="CleanShot 2022-01-11 at 12 11 26@2x" src="https://user-images.githubusercontent.com/40808343/149006278-5612ed30-7bd0-4151-ac8c-23f780861d57.png">
 
I feel like maybe then people would delete actions but be confused about how to add them back? But adding is more obvious since the "+" button always works and doesn't depend on a row being selected. So I think this is better. 

What do you guys think?

[MacMouseFixApp-2.1.1-Alpha-1.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/7849306/MacMouseFixApp-2.1.1-Alpha-1.zip)

**Comment by rtrembecky** [comment]
Thinking about the best UX here... I believe you are pretty fixated on those +/-. Personally, I would experiment with:
- making the plus button bigger, more eye-catching, maybe similar to `More...` above the list, having `Add shortcut...` (or `+ Add shortcut...`) below the list on the right,
- getting rid of the minus button and having e.g. ❌  or 🗑️  icon on the right of each line.

I can imagine yet another approach where one would disable shortcuts instead of deleting them, which I believe makes sense anyway - maybe I want to temporarily disable a shortcut but be able to turn it back on easily as well.

**Comment by noah-nuebling** [comment]
Hey Richard, thanks for your ideas!

I do like the idea of making the plus button larger. 

Eventually I would like the remapping UI to look like this. But that would require an overhaul of the whole UI, which is a while off at this point.
<img width="500" alt="CleanShot 2022-01-11 at 15 41 25@2x" src="https://user-images.githubusercontent.com/40808343/149046973-361264b0-a7c0-4bd1-ae7e-e452d874872c.png">

The current layout with the + - button exists to make the remapping UI fit into the existing design of the app. For that it needed it to be more compact, and so I decided to hide the '+' field behind a button.

I thought people would be familiar with the '+ - button' design pattern for tables, since Apple itself uses it a lot, but quite a few people have been confused about this, so I think it's worth addressing.

When it comes to having a visible remove button on each line, I do like the idea of making the option of removing rows more easily and immediatly visible, but I don't think there are any Apple apis for implementing something like that and I don't think I've ever seen it in a Mac app. So I think it might be hard to implement without looking out of place. Also it might clutter up the UI a little, but I'd have to see a mockup to form an opinion on that.

If you know any examples of Mac apps or other apps that have tables with inline delete buttons be sure to let me know.

I did replace the + - button with an 'Add Action...' button. You can check it out below. I think it looks a little strange? Maybe I'm just not used to it. But it does make things more easy to understand.

[MacMouseFixApp-2.1.1-Alpha-2.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/7851251/MacMouseFixApp-2.1.1-Alpha-2.zip)

Let me know if you have more suggestions.

**Comment by noah-nuebling** [comment]
Once the UI looks like above, maybe you could grey out the '-' button unless a row is selected. I think that would make it more obvious that '-' button targets the currently selected row.

**Comment by rtrembecky** [comment]
Even though I'm using Mac for nearly two years now, it seems I still think in terms of Windows and web apps 😄 I have no idea about the Apple design rules and what's possible and recommended in such native apps 😕 But I'm interested, so I'm already looking at e.g. https://developer.apple.com/design/human-interface-guidelines/macos/buttons/gradient-buttons/ 😄 
BTW1: Thanks for getting back to work on this in some capacity.
BTW2: The app actually doesn't work for me well for some months now, it just doesn't recognize the middle button, nor the 4 and 5... But I'll have a new Mac in a week so I'll be trying it then 😅

**Comment by sotakal** [comment]
Agreed with this being hard to identify in the app - I had to look up this thread to find a solution to disabling specific behavior.

**Comment by noah-nuebling** [comment]
I made some changes in version 2.2 to hopefully make the option to add and delete actions more discoverable, so I'll close this for now. Thanks everyone for chiming in!!
