### ISSUE TITLE
middle button click considerably slower than other buttons on mmf 2.1 [bug]

### ISSUE THREAD

**Issue by messham** [noah-nuebling/Mac-Mouse-Fix#208]
## Description

There is a very noticeable delay between clicking the middle mouse button and the action being executed. The test I have run is have both the middle button click and button 4 be mission control, try both and compare the delay. To make sure this isn't an issue with my own middle button I turn mmf off and click again and, as mission control is the default option, I compare the delay of this with it on. I did not have this delay with the previous version I was using (< 2.0, I think) .

I am currently unable to test this against previous versions because of the issue addressed in the 2.1 release notes (https://github.com/noah-nuebling/mac-mouse-fix/releases).

## Context

Mac Mouse Fix Version: 2.1.0
macOS Version: 10.15.7
Mouse Model: logitech g305

**Comment by dc-p8** [comment]
I'm having the same issue.

Deleting the "hold", "hold & drag" and "double click" on the mouse button make the single click much faster.
(select the line and press backspace)

**Comment by noah-nuebling** [comment]
Hey guys thanks for the feedback. 

Here's why this happens:

There needs to be a small delay for the 'Click' Action, when you have a 'Double Click' Action set up, otherwise you would always be forced to trigger the 'Click' Action, when you're only trying to trigger the 'Double Click' Action. 

As @dc-p8 noted, when you remove the 'Double Click' Action, the delay goes away. 

When you have no 'Double Click' Action, but still a 'Hold' and/or 'Click and Drag' Action set up, then the 'Click' Action will be triggered once you release the Mouse Button, not immediately when you press it. This needs to be the case, because otherwise you would be forced to trigger the 'Click' Action when trying to use the 'Hold' or 'Click and Drag' Action.

When you remove the 'Hold' and 'Click and Drag' Actions, then your 'Click' Action will be triggered immediately, as soon as you press the button.

Hope that makes sense! Let me know if you have any more questions or suggestions.

**Comment by messham** [comment]
Makes sense- thanks for the explanation!

**Comment by noah-nuebling** [comment]
Cool, no worries at all :)
