### ISSUE TITLE
2. Improvements for smooth scrolling [enhancement]

### ISSUE THREAD

**Issue by llll-jase** [noah-nuebling/Mac-Mouse-Fix#214]
## Description
This may include:

Additional (but simple) configuration options, such as being able to adjust the *snappiness* of scrolling and separating vertical/horizontal scroll speed.

Implementing a way to feel more like the trackpad or iPhone, such as how scrolling beyond the top/bottom of a page *bounces back* instead of abruptly stopping (without such things, scrolling feels kind of lifeless)

Making the "scroll speed" increments based on number of lines, like the mouse settings on Windows (E.g., make scroll speed "1" equal 1 line, and so on). This would be greatly appreciated by people who use both Mac and Windows and want consistency across devices.

## Rationale
Some other (free trial) apps have lots more customisations for smooth scrolling, but imo they can be confusing and make it more difficult to achieve the desired outcome. This app is beautiful in it's simplicity can provide user-friendly enhanced options while overcoming those hurdles for a better scrolling experience.

## Additional info
Using: Microsoft Surface Precision Mouse

**Comment by noah-nuebling** [comment]
Hey @llll-jase thanks for the thoughtful feedback!

I am considering adding more options for smooth scrolling but I’m not sure which ones to add. I agree that a lot of other apps with smooth scrolling have confusing options.

The “snappiness” does seem to warrant an option, since from the feedback I’ve gotten peoples preference on that varies a lot. 

The “bouncing” I plan to add in a future release. I want the scrolling to work just like swipes on a trackpad, and put a lot of work into that already. The “bouncing” will come with that, too. Although you have to make the scrolling extremely loose to really make it feel organic like on the trackpad. But you’ll see. I think it’ll be pretty good. :)

I’m not super familiar with the concept of “lines”. Could you elaborate what benefits it would bring for you to configure the scrolling in terms of lines? 

Also I think scrolling feels pretty tedious without any acceleration (although I think Apple acceleration is too much and hard to control). Do you have any ideas on how to combine a scroll speed setting in terms of “lines” with acceleration?

I’m also on the fence on whether I want to add separate scrolling speeds for horizontal and vertical scrolling. Could you elaborate on why you want that as well?

if you have any more ideas on what scroll settings to add that would also be very welcome.

Thanks!

**Comment by llll-jase** [comment]
oh nice, looking forward to it!

To clarify the lines, it's just when the travel distance per scroll down equals 1 line of text down. I'm not sure exactly what that measure is, but it's in mouse settings on Windows. It would benefit, for example, when scrolling in Finder as the next row of text will appear in the same location, so it's easier on your eyes.

Not sure about the acceleration, I just thought you could adjust "scroll speed". Right now, I'm using scroll speed = 3, but it only goes down about 2.75 lines (in Finder - Applications). Maybe I'm wrong about something though.

Also, the seperate horizontal/vertical is just an example of more options for people who need it (I personally don't, but thought it may be nice). Things like that can be kept in advanced settings

Thanks! Already a better app than many others

**Comment by noah-nuebling** [comment]
> To clarify the lines

Oh okay thanks I get it now! macOS does let you send line-based scroll events and it does work the way you described in Finder. But as far as I understand, you can only use them with non-smooth scrolling. For smooth scrolling, the events need to be pixel-based instead of line-based.

So it might make sense to send line-based scroll events in Mac Mouse Fix, but only if the user turns off smooth scrolling as well as acceleration. I'm not sure how I would present this in the UI without making things too complicated, and I feel that if the smooth scrolling is good most people would be happy with the pixel-based scrolls. I'll keep this in mind though.

This project might interest you though, if you haven't heard of it:
https://github.com/emreyolcu/discrete-scroll/

> Not sure about the acceleration

Mac Mouse Fix does indeed have scroll acceleration. It's just not so strong that it becomes jarring like the built in macOS scroll acceleration can be. You can't currently adjust the acceleration. The 'Scroll speed' slider just changes the base 'step size' - so how far it scrolls when you move the mouse wheel by a single tick - but not how that 'step size' grows when you scroll faster (which is what we call scroll acceleration). I plan on giving the user more options on this in the future. 

> Also, the seperate horizontal/vertical is just an example

Okay cool gotcha

> Thanks! Already a better app than many others

Thanks a lot! :)

**Comment by noah-nuebling** [comment]
Hi again @llll-jase,

Please to inform you that some of the features you requested are in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases) if you want to check it out!

There's now an option for the snappiness, as well as smartphone-like rubberbanding! I hope you like it!
Let me know if you have any thoughts on or issues with it!

Separate horizontal and vertical scroll speed settings and line-based scroll speed settings are not in the app, yet. If you still want those features please open a new enhancement request on those features specifically. 

Thanks!

**Comment by llll-jase** [comment]
Hi, nice improvements all around! My mouse feels more natural now. The options are also more intuitive and user friendly.

If there was one last piece of feedback to consider, it would be on how close you could make it feel like the native MacOS experience. For example, while the rubberbanding is very nice, it doesn't snap back the same.

Although using a mouse still isn't as seamless as using the trackpad, your app is definitely a must have for Mac users. Thank you for making something good even better :)
