### ISSUE TITLE
Compatibily with Right click  [enhancement]

### ISSUE THREAD

**Issue by Harut12345** [noah-nuebling/Mac-Mouse-Fix#219]
## Description
Add possibility to replace all middle button functions (like mission control, show desktop etc ) on right click (Except middle click)

## Rationale
There is no problem with the current configuration it's just a personal preference

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi Harut thanks for your feedback! I won't answer in detail now, but know that I'm taking your feedback into consideration and that I've already spent some time thinking about it. 

I'm closing this now to clean things up because I'm moving the topic of allowing the Primary / Secondary Mouse Button to Issue #364. Hope that makes sense! Let me know if you have more questions.

**Comment by noah-nuebling** [comment]
I did answer in detail! See #364.
