### ISSUE TITLE
Long Middle Click Delay [bug]

### ISSUE THREAD

**Issue by choodique** [noah-nuebling/Mac-Mouse-Fix#225]
## Description

Long Middle Click Delay [bug]

## Steps to reproduce

Using browser tabs as an example:
- Press Middle click on a tab, at the same moment move the cursor to the next tab

Waiting - the tab on which the Middle click was executed will close

Reality - the tab to which the cursor has moved is closed 

![Screenshot](https://0x0.st/ooRm.png)

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.1
Mouse Model: Logitech MX Anywhere 3

## Additional Comments

Video: https://0x0.st/ooRa.mov

---

**Comment by EvansMatthew97** [comment]
Delete the double middle click binding.

![image](https://user-images.githubusercontent.com/10000036/151347624-bda01f56-2254-4fb2-9168-860763ed6a82.png)

With the binding enabled, it waits for a bit to determine whether you pressed the button once or twice. Otherwise it would just trigger a single middle click twice. When disabled, it doesn't need to perform this check.

**Comment by choodique** [comment]
> Delete the double middle click binding.

Wow! It's work!
Thanks for the tip!
