### ISSUE TITLE
Stops working when switching profiles [bug]

### ISSUE THREAD

**Issue by PuzzleHeaded555** [noah-nuebling/Mac-Mouse-Fix#230]
## Description

I think I figured out why. When I switch to another profile on my Mac and then switch back the scrolling stops working on my mouse. Then when I switch to the app, it still shows it's enabled. I have to disable and enable. I have started the app in the other profile. Not sure I've started it each time.

## Steps to reproduce

1. Mac Mouse Fix was enabled.  
2. Switched Mac profiles
3. Scrolling wasn't working on 2nd profile so I disabled it and enabled it.
4. Switched back to 1st profile
5. Scrolling wasn't working on 1st profile so I disabled it and enabled it.
6: Approximate time was 1:58pm 1/28/22

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 10.15.7
Mouse Model: Microsoft Trackball Explorer 1.0

## Additional Comments

–

---

### Console Logs

https://pastebin.com/BiP2Axyz

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Thx for filing a report @anim8rav! 

Unfortuately, this issue is pretty tricky to fix. 
I plan to rewrite the whole input capturing system eventually, and when I do that I'll be able to address this properly. But I don't have too much time to work on the project so please don't hold your breath for a fix.

However in the meantime there are 2 workarounds:
- Disable and then re-enabe the app after switching profiles
- Log out of the current profile before switching to a new profile

Hope that helps!

**Comment by noah-nuebling** [comment]
Closing this Issue so all discussion on this bug is centralized in #93
