### ISSUE TITLE
Click and Drag functionality for Button 4 & 5 [enhancement]

### ISSUE THREAD

**Issue by BenPearo** [noah-nuebling/Mac-Mouse-Fix#234]
## Description
Support click & drag shortcuts for buttons 4 & 5

## Rationale
It would be very convenient for users to use their thumb buttons to perform swiping operations. The thumb requires virtually no movement to reach the button, and the button could still be used for back/forward operations on single click. 

The middle mouse button is not a frequently used input for most users, which makes it sub-optimal for performing operations as natural as swiping between spaces as you would with a magic mouse or trackpad. Users who have buttons 4 & 5 likely use them frequently when browsing, and their proximity to the thumb make their use extremely natural. Supporting these buttons would be in the spirit of this application, to make the use of a 3rd party mouse feel natural and efficient.

**Comment by noah-nuebling** [comment]
Hi Ben! Try the “+” button ;)

I’ll plan to make this more obvious in a future release.

Let me know if you have any more questions or feedback!

**Comment by EvansMatthew97** [comment]
Click & drag on Mouse 4, Mouse 5 and the Gesture button doesn't work for me either. I'm using a Logitech M720. Middle click works perfectly, but I want to retain the middle click and drag functionality for panning in most apps.

I also have to connect via Bluetooth for it to recognise any input other than middle click.

**Comment by BenPearo** [comment]
> Hi Ben! Try the “+” button ;)
> 
> I’ll plan to make this more obvious in a future release.
> 
> Let me know if you have any more questions or feedback!

Thank you for letting me know, Noah. This works exactly as I hoped! I have had difficulty finding usage documentation with this application, so making it more obvious is a great plan. It would be a good idea to offer a dropdown of supported gestures when adding a new shortcut - clicking and dragging in the provided box took a couple of tries.

**Comment by noah-nuebling** [comment]
@EvansMatthew97, I'm using an M720, too. It should work fine, except for the gesture button. Have you tried Clicking-and-Dragging in the '+' field?

Your issue with using the mouse via Bluetooth is quite weird. My M720 works the exact same under Bluetooth and via USB. The only thing I can think of is that some other Mouse Driver like Steer Mouse or Logitech Options is interfering with Mac Mouse Fix. And maybe that other driver has configured your mouse to work differently via Bluetooth vs via USB.

You can test if Button 4 and Button 5 work normally without Mac Mouse Fix, by clicking them over a link in Safari (after disabling Mac Mouse Fix). If the buttons work normally, then the link should open in a new tab. If that doesn't happen, then your side buttons don't send normal Button 4 and Button 5 events. Likely due to some other driver interfering.

Note that certain drivers like Logitech Options and SteerMouse can reconfigure Logitech mice in a way that still persists, even after you uninstall the respective driver.

I hope that helps a little! Let me know if you find anything.

**Comment by EvansMatthew97** [comment]
@noah-nuebling Uninstalling Logi Options makes it work 👍 

It's a pity that the gesture button doesn't work, because I could retain the use of my forward/backward buttons. But this app works so much more consistently than the Logi Options gesture controls it's worth it.
