### ISSUE TITLE
Middle button mapping not working [bug]

### ISSUE THREAD

**Issue by prekopam** [noah-nuebling/Mac-Mouse-Fix#267]
## Description

Hi! I have a Logitech M185 mouse with 3 buttons, and before the 2.0 update holding my middle button was mapped to open the Launchpad. After 2.0 it is not working even though it is configured in the settings. Normal behavior of the middle button is still active, like closing tabs etc.

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: MacOS 10.14.6
Mouse Model: Logitech M185

**Comment by noah-nuebling** [comment]
Hi @prekopam, thanks for reaching out!

There seem to be issues with macOS 10.14 Mojave. See the ['macOS 10.14 Incompatibility' Issue Category](https://github.com/noah-nuebling/mac-mouse-fix/labels/macOS%2010.14%20Incompatibility).

I want to look into this but I'm currently having trouble trying to debug Mac Mouse Fix on older macOS versions.

If anyone has any tips here I'd greatly appreciate it!

I also asked a question about this on StackOverflow: https://stackoverflow.com/questions/74224459/how-to-debug-mac-app-on-older-macos-version

**Comment by noah-nuebling** [comment]
Hey @prekopam, I just released an update to Mac Mouse Fix (version 2.2.3) specifically to make the experience better on older macOS versions!

It probably won't fix your issue since I unfortunately couldn't reproce it so far.  But you can try it out [here](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.3).

I'll close this issue now so all the discussion around this problem is focused in Issue #246. 
If you think your issue is different from the one described in #246, please open a new issue or let me know so I can reopen this one.

Oh and [this comment](https://github.com/noah-nuebling/mac-mouse-fix/issues/246#issuecomment-1296310576) contains info on how you can help figure this problem out if you're interested.
