### ISSUE TITLE
Invert side buttons 

### ISSUE THREAD

**Issue by JonasGessner** [noah-nuebling/mac-mouse-fix#27]
For some reason the side buttons on my mouse are detected in an inverted order, making the back button trigger the forward action and vice versa. Would you consider adding an option to invert the side buttons?

**Comment by noah-nuebling** [comment]
Hi Jonas, thank you for your feedback! 
I'm considering implementing a more flexible remapping interface at some point so that people who have more buttons on their mice can remap them to cool functions using Mac Mouse Fix. This would also solve your issue.
Unfortunately I don't have too much time to work on the project, so please don't expect anything too soon.
In the meantime please check out [SensibleSideButtons](https://sensible-side-buttons.archagon.net) it's a neat little open source project, which provides the feature you're looking for.

**Comment by hrhnick** [comment]
I would just prefer using the back button to move to the right desktop!
