### ISSUE TITLE
Sticky Multi-touch zoom simulation [bug]

### ISSUE THREAD

**Issue by minimum91** [noah-nuebling/Mac-Mouse-Fix#270]
## Description

I was delighted when I discovered that Mac Mouse Fix supported multitouch zoom simulation so I started using it in my day to day job right away. But it soon became apparent that something is causing it to get stuck more often that not.

## Steps to reproduce

⌘   scroll up, or ⌘   scroll down

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 10.14.6
Mouse Model: Logitech G305

## Additional Comments

Attaching a video link with the observed behaviour. That said it must be noted that I use other mouse and keyboard behaviour changing apps, like karabiner, better touch tool and others. 

https://mega.nz/file/ffIgQYIQ#nsHDbcog0GymBPlUZDhEr4YxvZNWsqwfdLYU6tOK4_Q

---

### Console Logs

–

### Crash Reports

–

**Comment by krackers** [comment]
I reimplemented a zoom simulation based on the reverse-engineering in this repo, and I'm noticing the same thing. From playing around, it seems/behaves like the CGEvent created via `postMagnificationEventWithMagnification` is "relative" to the current zoom state.

Or to put it another way, the zoom doesn't seem to kick in until the cumulative sum of the `magnification` for the zoom events exceeds the current page zoom state.

 If you start with the page fully zoomed out, then things behave as expected, and so long as you don't let go of the modifier the cumulative sum keeps getting updated so things work fine. But when you start with the page partially zoomed in, then you get the delay due to the above.

I don't know how this works when using the internal trackpad. 

Edit: Nevermind, I think the behavior I'm seeing is instead explained by the fact that the mapping between the `magnification` and resulting page zoom is non-linear. That is, there is indeed a "stickiness" at the beginning of the event that must be overcome. I con't know if this is what you observed though, since the stickiness should be symmetric for both zoom in and zoom out. I was able to work around this by weighting the initial few events higher than the rest, and it seems to behave ok.

**Comment by akash329d** [comment]
Weighting the first few events seems like a good idea to resolve this. Did you have any luck figuring out how this works with a trackpad though? Curious why we don't notice the non-linear response there.

**Comment by krackers** [comment]
I'm not sure about the internal trackpad. If you do the gesture very slowly, I also sense a bit of stickiness there, but that might just be because the trackpad doesn't actually recognize it as a pinch-zoom gesture until it collects enough samples. You could try running [Calftrail's TouchExtractor](https://github.com/calftrail/Touch/tree/master/TouchExtractor) and filtering the log messages on the pinch-zoom events to see how the value of `magnification` changes over time.

Also while weighting the initial few events does seem to make it better for me, it still doesn't feel 100% smooth. I'm also not sure if the weighting is something that's generalizable for all users because different scroll wheels will behave differently in terms of resolution of reported events and tick rate. Maybe instead of fixed weights you need some system where you have the user spin the wheel for a bit and then use the sampled data to calculate the appropriate weights?

**Comment by minimum91** [comment]
Almost forgot to chime in here. Most obvious of this was resolved when I stopped using Karabiner.
