### ISSUE TITLE
Horizontal scroll reverse [enhancement]

### ISSUE THREAD

**Issue by milohuang** [noah-nuebling/Mac-Mouse-Fix#293]
## Description
I have a Logitech M720 and use the wheel to tile left or right to view large chart on Excel. I wish horizontal scroll can be inverted too. Thanks a lot for this nice app, help a lot :) 

## Rationale
To make more use out of the wheel on certain type of mouse.

## Additional info
–

**Comment by daaaaaaaaaniel** [comment]
+1 to this (and similar proposals like https://github.com/noah-nuebling/mac-mouse-fix/issues/151). On logitech mice like this (and the MX ERGO that I use) the vertical scroll is activated a spinning wheel, while horizontal scroll _slides_ rather than spins. On devices with this type of physical layout, it makes a lot of sense to have natural (inverted) scrolling in one axis and standard (uninverted) scrolling in the other axis. We should have the ability to set the scrolling direction independently for each axis.

**Comment by noah-nuebling** [comment]
Hey guys thanks for reaching out! 

In the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases), it will now smooth and invert horizontal scroll input from your mouse!

MMF 2 would just ignore horizontal input from your mouse. 

There's no way to invert the horizontal scroll direction independent from the vertical one. But I hope this improves your experience!

If you still would like to see a separate option for inverting just the horizontal scroll direction, please open a new issue on that. Thanks!
