### ISSUE TITLE
Rubber banding effect [enhancement]

### ISSUE THREAD

**Issue by DeepFriedPotato** [noah-nuebling/Mac-Mouse-Fix#296]
## Description
Is it possible to add rubber banding effect to the scroll view (the elastic effect when reaching the end of the scroll view)?

## Rationale
It feels unnatural to stop immediately like hitting a brick wall.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi @DeepFriedPotato thanks for your enhancement request!

Please to inform you'll get that rubberbanding effect when scrolling under the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

This is possible because Mac Mouse Fix now closely emulates the way that Apple's Trackpad driver works!

Hope you like it and let me know if you have more thoughts or requests!
