### ISSUE TITLE
Hi Noah, Why don't you allow secondary mouse button to be used with drag gesture ?  [other]

### ISSUE THREAD

**Issue by melyaaka** [noah-nuebling/Mac-Mouse-Fix#321]
please can you enable this feature ? I am using a very minimalist mouse and I dont have other buttons to take advamtage of gestures. I only have the secondary button

**Comment by noah-nuebling** [comment]
Hi @melyaaka thanks for your feedback! I won't answer in detail now, but know that I'm taking your feedback into consideration and that I've already spent some time thinking about it. 

I'm closing this now to clean things up because I'm moving the topic of allowing the Primary / Secondary Mouse Button to Issue #364. Hope that makes sense! Let me know if you have more questions.

**Comment by noah-nuebling** [comment]
Hey @melyaaka, I just posted an explanation for my reasoning behing the way things currently work [here](https://github.com/noah-nuebling/mac-mouse-fix/issues/364#issuecomment-1241626849)
