### ISSUE TITLE
Doesn't capture button presses since Ventura - KATAR Pro Wireless [bug]

### ISSUE THREAD

**Issue by fnschmidt** [noah-nuebling/Mac-Mouse-Fix#362]
## Description

Using 2.2.1 Beta 3 and the mouse's USB dongle.

Worked fine in Monterey, but since Ventura the preset button actions like Mission Control/Spaces don't work; neither does button detection when trying to map to a new button. Only button 1 and 2 trigger the message that they can't be remapped.
Smooth scrolling still works.

In the event log, there are a few messages like:
0x.......... TCC deny IOHIDDeviceOpen
Error opening device. Code: e00002e2

## Steps to reproduce

Use (newest) Ventura beta, and (probably) this specific mouse

## Context

Mac Mouse Fix Version: 2.2.1 Beta 3
macOS Version: Ventura beta 22A5331f
Mouse Model: Corsair KATAR Pro Wireless

## Additional Comments

–

---

### Console Logs

https://pastebin.com/W5Q09KFK

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @greybaron, thanks for opening this issue and adding so much detail! The line you pointed out is very important I think.

> TCC deny IOHIDDeviceOpen
Error opening device. Code: e00002e2

IOHIDDeviceOpen is necessary to handle your Buttons, so this would explain the behavior you see.

TCC stands for “Transparency, Consent and Control” and it is a system service that basically manages the permissions you give to apps. Error code e00002e2 is kIOReturnNotPermitted. 

So the issue is that there are some permissions that Mac Mouse Fix doesn’t have but which it needs to run.

I would assume it’s the Accessibility Permissions as those are the only permissions that Mac Mouse Fox normally needs.

The thing that is weird is that the accessibility framework seems to tell Mac Mouse Fix Helper that it *does* have accessibility permissions, otherwise it shouldn’t even try to call IOHIDDeviceOpen.

So off the top of my head I can think of these ideas for what to try next:

1. Ventura has these really weird issues if you have multiple versions of the same app installed. Make sure you delete all versions of Mac Mouse Fix except the most recent one (and don’t forget to empty the trash) and then restart your computer and try again.
2. If that doesn’t work maybe there’s something else wrong with the permissions. Go to the Privacy and Security settings and see if the Accessibility Permissions are turned on or if any other permissions that might be relevant are turned off. Maybe try removing Mac Mouse Fix Helper from the Accessibility permissions, restarting your computer, and then try again.
3. Maybe Mac Mouse Fix just doesn’t have accessibility permissions (and is still calling IOHIDDeviceOpen due to a bug or something) and something else is failing so the main app can’t display the appropriate feedback to you. If that’s going on, it may also help to delete all other versions of Mac Mouse Fix and then restarting to help the main app and the helper app to communicate properly. Or of course to switch on Accessibility Permissions if they are turned off.
4. There’s also the message `attempted to call TCCAccessRequest for kTCCServiceAccessibility without the recommended com.apple.private.tcc.manager.check-by-audit-token entitlement` in the logs you sent. I think I’ve seen that message a long time ago. I think it’s always been there and never caused any issues, but I should probably fix that. Maybe it has something to do with it. Let me know if you continue to have issues and I’ll try to add those entitlements and we’ll see if that works

**Comment by fnschmidt** [comment]
Thank you for the detailed reply. I did upgrade from another build (I think it even was the unofficial build/workaround for early Ventura versions, so assuming the dev signature changed, that could also cause issues). 

I'm currently fighting macOS on this, any time I disable accessibility perms for MMF, macOS completely softlocks. Maybe Ventura is buggy, or that issue is related

**Comment by noah-nuebling** [comment]
Ohh I’m sorry I didn’t mention that, always disable any apps before you revoke its accessibility permissions. Otherwise you get the soft locking. Very annoying, but it’s a macOS issue that I can’t really do anything about I think.

Sometimes it stops after wiggling my mouse around for 20 minutes but I usually just force restart my computer.

**Comment by fnschmidt** [comment]
I removed the permission, deleted MMF and rebooted, then reinstalled. It works now!

Maybe as a workaround there is a somewhat easy way to detect this condition, and show the user these tips to solve the issue.

**Comment by noah-nuebling** [comment]
Great! Really glad that’s sorted out! 

> Maybe as a workaround there is a somewhat easy way to detect this condition, and show the user these tips to solve the issue.

Yeah that’s a good idea. I’m hoping this will get resolved before Ventura releases, but if not, the permission errors when calling IOHIDDeviceOpen despite the accessibility framework telling us we have the relevant permissions is a weird thing we could detect and maybe warn the user about with some solution ideas.

Thanks for helping to figure this stuff out!

**Comment by fnschmidt** [comment]
Gladly, this program is amazing 😉

**Comment by MSamiulHasnat** [comment]
<img width="580" alt="Screenshot 2022-10-30 at 8 56 28 PM" src="https://user-images.githubusercontent.com/58338543/198885496-abd6398c-7481-46be-ac5e-6f52523dda44.png">
But it still not working for me, I've tried every possible and described way but it stays the same. In the screenshot, I removed all the default functionality of the middle button. After that, I was trying to add the middle button by clicking the middle button on the plus sign and it doesn't detect it. Should I step down to macOS 12?

**Comment by fnschmidt** [comment]
Just to clarify. Have you done _all_ of these steps in this exact order?

1. disable Mac Mouse Fix (in the main window)
2. move Mac Mouse Fix to the Trash, then _empty_ the trash
3. restart your Mac
4. Download and reinstall the newest version, move it to Applications and start it
5. grand it all permissions it needs (it should ask for those. If not, go to Settings and make sure it has Accessibility permission)

If you have and it still isn't working, it is most likely a different issue. You should create a new issue and add details like Console logs.

**Comment by MSamiulHasnat** [comment]
Yes, I did it in exact order.
It could be a different issue.

**Comment by noah-nuebling** [comment]
Someone emailed me with the exact same symptoms that @samiulhsnt reported in #424 and they told me some additional info that suggests it's not the same problem that @greybaron had.

So @samiulhsnt I think you're right and your issue is different from @greybaron's.

I plan to work on trying to solve your issue very soon!
