### ISSUE TITLE
Buttons 5 and 6 are not detected [bug]

### ISSUE THREAD

**Issue by manudevelopia** [noah-nuebling/Mac-Mouse-Fix#376]
## Description

application 'Buttons' tab does not recognise buttons 5 and 6 from my Logitech trackman marble when I use any of them. 1 and 2 are recognised, and alert about 'Primary Mouse Button ....' is shown.

I noticed also that if 'Shown in menu bar' is active, icon disappears if I click on 5 or 6 button/

## Steps to reproduce

1. Open app and "Enable Mac Mouse Fix', set active 'Show in Menu Bar'
2. Go to "Buttons" tab
3. Move the cursor into dark grey square
4. Click 6 or 5 button

Icon menu bar disappears and no action is detected on app

## Context

Mac Mouse Fix Version: 3.0.0 Beta 3
macOS Version: Monterey 12.5.1
Mouse Model: Logitech trackman marble

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

https://pastebin.com/7q2s1UYc

**Comment by noah-nuebling** [comment]
Hi @manudevelopia thanks for your feedback! 

Mac Mouse Fix doesn't fully support most Logitech Devices, yet, because some of their buttons send special Logitech events that Mac Mouse Fix can't interpret.
I wanna add full Logitech support in the future, but it's a while off at this point.

In your case, the Helper App crashes when you click a button though, that is not supposed to happen. 
If you can reproduce the crash again with [this build](https://github.com/noah-nuebling/mac-mouse-fix/files/9585532/MacMouseFixApp-ForManu.zip) of the app, and then post the crash report, that should help us figure out what's going on. Thanks!

**Comment by manudevelopia** [comment]
Sure! here you go the crash report, it has been taken with provided build (version 3.0.0 Beta 3 (18469)):

https://pastebin.com/zteAYemF

**Comment by noah-nuebling** [comment]
Thanks very much! 

I took a look at the crash report, and it says it crashes because of an assertion failure in a function that doesn't have any `assert()` statements, which is confusing. And it also doesn't provide any line number for where this crash is triggered.
I googled around a little bit but I don't know how to approach debugging this right now. 

I'll look into it more in the future. For now I think it's best to let it rest and work on it more if other people have the same issue or when I get my hands on hardware that also produces this crash. 

But if anyone else has any ideas what might be happening or how to approach debugging it I'd really appreciate that! Thanks!

**Comment by manudevelopia** [comment]
Thank you, I will check it in new beta vesions to see if works or throws a different error.

I have tested 3.0.0 Beta 3 (18468) on other macbook pro with Big Sur and works perfect, so I suspect that could be related with my current Monterey macbook pro setup or related with osx version.

**Comment by noah-nuebling** [comment]
@manudevelopia thanks for doing more research on this! I just double checked on my intel Mac running 12.6 and it seems to be capturing buttons fine as well.

**Comment by trivita** [comment]
button 5 isn't detected on my razor basilisk hyperspeed. monterey latest update. m1 pro

**Comment by manudevelopia** [comment]
[3.0.0 Beta 4](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-4) working perfectly, buttons are recognized and tray icon keeps, great job!!!

**Comment by noah-nuebling** [comment]
Thanks!! :)

**Comment by noah-nuebling** [comment]
I don't really know why the buttons would be recognized now if they weren't before but that's nice!

Let me know if you have more questions or issues.
