### ISSUE TITLE
Add an option to disable bouncing effect in ver. 3.x [enhancement]

### ISSUE THREAD

**Issue by ib0ndar** [noah-nuebling/Mac-Mouse-Fix#378]
## Description
One of the new features in the 3.x versions seems to be a bounce back effect on the top and bottom screen edges. It would be great to add a switch in the preferences to turn it on and off.

## Rationale
Such option will solve the issue with sometimes slow and laggy bouncing effect. Some users may prefer to have this bounce while others like me don't expect it with mouse scroll wheel, it often feels slow and laggy and really works best with trackpad only.

## Additional info
I am hugely pleased with many new options like an ability to exclude mouse keys from monitoring etc. Big thanks for your work! Your app is the best in its class!

**Comment by nickcolea** [comment]
I think this also makes Safari horizontal scrolling act like back/forward buttons on pages when you hit the edge of the screen while scrolling. 

This is extremely annoying and makes you go back unintentionally. It's similar to the "inertia" effect, that I have disabled, but this issue still persists. The only way to stop it is to disable scrolling control altogether.

**Comment by noah-nuebling** [comment]
Hey guys thanks for your feedback!

I'm sorry you're not liking some of the changes to scrolling in MMF 3. I want MMF 3 scrolling to feel just as responsive as MMF 2, and I plan to work on my early 2015 MBP to make sure it feels good even if the computer is dropping frames.
For now, you should be able to get a more responsive feel by turning off the "Intertial Scrolling" option. More on that [here](https://github.com/noah-nuebling/mac-mouse-fix/discussions/366#discussioncomment-3686113).

The bouncing effect is something that macOS does automatically due to the more advanced trackpad-like scrolling simulation in MMF 3, it's unfortunately not just a switch I can turn off. This is also the reason that you can now navigate between pages in Safari by scrolling horizontally. 

To undo this, I'd have to reengineer large parts of the scrolling algorithms and it would change how the scrolling interacts with many things across macOS. For example it would take away the ability reveal quick actions in Mail by scrolling and, it would totally break scrolling in Preview's single page mode.

Also, I personally like the bouncing effects and the ability to do little extra things by scrolling like navigating between pages in Safari, and I assume that many users also see this as a cool thing.

So I hope you understand that I don't consider it a good idea to remove these things.
But I'm keeping my mind open and I'll think about this more. And hopefully I can make some changes to improve your guy's experience.

To help with that it would be really great to understand your guys' issues better:

@ib0ndar, if you have time could you send a video of the laggy bouncing effect you've observed, or describe the exact circumstances where the laggy bouncing occurs? Also which Mac model and which macOS version are you using?

@nickcolea In which situations have you gone back and forward unintentionally? The horizontal scrolling should act just like scrolling on a trackpad does. If there's a difference, that might be a bug that I can fix. A video would also be really handy.

Thanks guys!

**Comment by ib0ndar** [comment]
Hi @noah-nuebling ,

Totally understand your point, without knowing all the details of implementation it is hard to evaluate how hard it is to modify a function.  I will try to capture a video to show the difference between bouncing effect with trackpad and mouse.

Nevertheless, I like MMF 3 much better than 2 and a couple of hours ago bought the license 🙂

**Comment by nickcolea** [comment]
> @nickcolea In which situations have you gone back and forward unintentionally? The horizontal scrolling should act just like scrolling on a trackpad does. If there's a difference, that might be a bug that I can fix. A video would also be really handy.
> 
> Thanks guys!

The situation happens on all websites when using the horizontal scroll wheel on my mouse (MX Master 3 Mac).

MMF 2 didn't have this issue at all for the horizontal scroll wheel. 

I really like the new feel of MM3 scroll overall, but this issue with the horizontal scroll being unusable is a huge problem for the work I do, so I have to use MM3 just as a button remapping tool and waste the potential. Hopefully this is something you can identify as a bug, since it's a problem with all websites. 

The vertical scroll is just awesome and much better feeling than MMF 2. Would be happy to pay for a licence once MM3 is out of beta. 💯

**Comment by ib0ndar** [comment]
@noah-nuebling , I've sent you links to videos directly on your email. BTW, while playing with several settings in the app, I think I've found the way to reproduce that choppiness and slowness of the bouncing animation - you need to have 'smooth scrolling' enabled **and  'with inertia' disabled**. If I enable 'with inertia' the issue is gone, but inertial scrolling with discrete mouse wheel is not such a great idea.

**Comment by noah-nuebling** [comment]
I understand @ib0ndar's issue now. The scroll bounces take too long and feel weird when the "with Inertia" option is turned off. I should be able to make that feel better in the future.

@nickcolea Thanks for getting back and for the kind feedback! I'll get an MX Master next week to hopefully get a better understanding, but as of now I'm not totally sure what's going on here.

I'll try to explain my current thinking:

If you're on a site that doesn't have any vertically scrolling content, like GitHub, then it should not be a bothersome thing that the horizontal scroll wheel lets you go back in your browser history, because it's just an additional option and otherwise the horizontal scrollwheel would do nothing. 

If so, then I can only think of two problems:

A. You're accidentally scrolling on the horizontal scrollwheel. I would think that's unlikely since Logitech would've build their mice to prevent this.
B. You're using some website that **does** have horizontally scrolling content, and Mac Mouse Fix won't let you scroll that horizontal content properly and instead goes back and forward in your browser history. I've heard of this issue when using Chrome with Google Sheets, but I thought that was an isolated bug that only happens when you use Google Chrome and Google Sheets together. So if there are other places where this happens, please let me know so I can investigate that bug further.

Let me know if that's what's going or if I'm misunderstanding something here or if there's an entirely different reason for your troubles.

Thank you!

**Comment by nickcolea** [comment]
> @nickcolea Thanks for getting back and for the kind feedback! I'll get an MX Master next week to hopefully get a better understanding, but as of now I'm not totally sure what's going on here.
> 
> I'll try to explain my current thinking:
> 
> If you're on a site that doesn't have any vertically scrolling content, like GitHub, then it should not be a bothersome thing that the horizontal scroll wheel lets you go back in your browser history, because it's just an additional option and otherwise the horizontal scrollwheel would do nothing.
> 
> If so, then I can only think of two problems:
> 
> A. You're accidentally scrolling on the horizontal scrollwheel. I would think that's unlikely since Logitech would've build their mice to prevent this. B. You're using some website that **does** have horizontally scrolling content, and Mac Mouse Fix won't let you scroll that horizontal content properly and instead goes back and forward in your browser history. I've heard of this issue when using Chrome with Google Sheets, but I thought that was an isolated bug that only happens when you use Google Chrome and Google Sheets together. So if there are other places where this happens, please let me know so I can investigate that bug further.
> 
> Let me know if that's what's going or if I'm misunderstanding something here or if there's an entirely different reason for your troubles.
> 
> Thank you!

Indeed, you are correct. Case A wouldn't apply, as that is simply user error, and the mouse is pretty well designed to prevent that.

I am using only Safari as my browser and have tested both Safari and Safari Technology Preview, so I could rule out any temporary bug on the browser side. 

The issue happens on websites that display table form data. [Always, when you hit the edged of the table, the scroll function turns into back/forward](https://www.10kreader.com/company/aapl/financials). This is really annoying when dealing with any forms that require you to scroll horizontally and then back to the first column. Of course, I could be extra careful, but with the added inertia feeling to animation from macOS, it's quite difficult to anticipate and stop this action from happening. 

Another example would be charts and other "zoom" type elements that seem to be problematic. Once case is [this website](https://www.chicagofed.org/publications/nfci/index) where the scroll works at the same time as the back/forward function on these particular charts. Google Sheets is not an issue most of the time, as it seems to separate well from the cells area and UI elements. 

Thanks for looking into this. 👍

**Comment by noah-nuebling** [comment]
@nickcolea thanks a lot for that detailed feedback! It was helperful for me to understand the various issues that were going on.

In the latest [3.0.0 Beta 6](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-6) there is now an option to turn off the bouncing effect and the scrolling to go to the previous page, by unchecking the "Trackpad Simulation" option.

I'll close this issue now as I assume it's been resolved. If you have more troubles or questions, let me know.
