### ISSUE TITLE
I don't have a credit card, and Gumroad has been banned by the Great Wall in China [enhancement]

### ISSUE THREAD

**Issue by Vikingama** [noah-nuebling/mac-mouse-fix#380]
## Description
I can't visit the Gumroad. The Payment will be failed, When I pay the licence in the Gumroad with PayPal using a VPN. What should I do?

## Rationale
Please support AliPay or WeChat Pay

## Additional info
–

**Comment by Vikingama** [comment]
Could you publish MMF on App Store, please

**Comment by Vikingama** [comment]
PayPal's Donation doesn't support China

**Comment by Vikingama** [comment]
![Google Chrome-2022-09-20-10 58 01](https://user-images.githubusercontent.com/26019582/191240663-0748e1dd-1ea5-42af-b47f-c0b411af1e48.png)

**Comment by Vikingama** [comment]
MMF are so important to me!

**Comment by jdjxk** [comment]
Same problem. Please support Alipay. Thanks!

**Comment by noah-nuebling** [comment]
Hey guys, thanks for the feedback!

I'll talk to them some more about this, but currently it looks like Gumroad, the payment provider for Mac Mouse Fix don't have any plans of supporting Ali Pay or Chinese Union Pay cards, since Gumroad is blocked in China.

It would be a lot of work to provide an alternative payment method to Gumroad, and it would probably create some delays if I wanted to integrate it before MMF 3 releases.

So I thought maybe I could just make MMF 3 **free** for all users that have their region and/or language set to mainland China in System Settings, until I can provide a payment solution that works in China.
Do you guys think that would make sense?

The idea is that, to use MMF 3 for free, you'd have to set your region to mainland China:

<img width="827" alt="Screenshot 2022-09-21 at 05 24 02" src="https://user-images.githubusercontent.com/40808343/191407691-18976c72-58c6-451f-8b4d-f7fcf76e92e1.png">

And maybe also have your language set to Chinese:

<img width="827" alt="Screenshot 2022-09-21 at 05 20 30" src="https://user-images.githubusercontent.com/40808343/191407708-ecd05dd5-42b8-4470-8900-07c0c9453afb.png">

But that probably doesn't make sense since some users in China will want to use their computers in another language?

Let me know what are your thoughts on this!

> Could you publish MMF on App Store, please

I would love to bring MMF to the App Store but that's unfortunately not possible since it uses some system functions that Apple forbids.

> PayPal's Donation doesn't support China

Thanks for wanting to donate!! You probably know this, but just to be clear: A donation is not needed to use MMF 3. It doesn't do anything except put a smile on my face :)

As a side note: 

I talked to one user in China who could buy the app through PayPal, but they said it was only possible because they had a special credit card that lets them pay in foreign currencies.

**Comment by Vikingama** [comment]
My thoughts about 
> "Could you publish MMF on App Store, please" 

is that I could pay for the MMF through the App Store.

Thank you so much for 
> "So I thought maybe I could just make MMF 3 free for all users that have their region and/or language set to mainland China in System Settings, until I can provide a payment solution that works in China."

I will try to apply a "special credit card" that could let me finish this payment.

Thank you very much.

**Comment by CavalloneChen** [comment]
Thanks Noah! You are so generous and I really enjoy using MMF.

**Comment by BingoKingo** [comment]
You can try Paddle.com which supports [Alipay in early access](https://www.paddle.com/help/start/intro-to-paddle/which-payment-methods-do-you-support).
