### ISSUE TITLE
3.0.0 Beta 3 (18468)  Button4 , Middle Button and Button5 invalid on MX Master3 [other]

### ISSUE THREAD

**Issue by icesk** [noah-nuebling/Mac-Mouse-Fix#383]
After reboot system those buttons can be detected.But several minutes later or hours, those buttons not invalid. macOS Monterey 12.6

**Comment by noah-nuebling** [comment]
Hey @icesk, thanks for reaching out! 

I don't know how this could be caused by Mac Mouse Fix. If nothing about this changes when you disable and re-enable Mac Mouse Fix, then I'm **pretty** sure it's not because of Mac Mouse Fix. 

My best bet would be that there is some other mouse software like Logitech Options or SteerMouse causing this, or that it's a macOS bug if you're running a macOS Beta.

Hope that helps a little! Let me know if you find out more or have more questions.

**Comment by icesk** [comment]
@noah-nuebling Thank you for your reply. I'll check it again.
