### ISSUE TITLE
Smooth scrolling causes issues with scrolling in the buttons tab [bug]

### ISSUE THREAD

**Issue by rishifter** [noah-nuebling/Mac-Mouse-Fix#416]
## Description

When smooth scrolling in the scrolling tab is enabled on 3.0.0 beta 4, scrolling inside the buttons tab, in the table where all the click/actions are becomes impossible. The only way to move up or down is using arrow keys on the keyboard. 

## Steps to reproduce

1. Turn on smooth scrolling.
2. Visit buttons tab and have enough actions to scroll and try scrolling.
3. Disable smooth scrolling and try scrolling again. 

## Context

Mac Mouse Fix Version: 3.0.0 Beta 4
macOS Version: 12.6
Mouse Model: Logitech MX Master 2s

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi @rishifter thanks for your feedback! 

I think this is the same problem as #413. That problem should be fixed in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5).

If 3.0.0 Beta 5 still doesn't work for, you please open a new issue or let me know so I can reopen this one.

Thanks!
