### ISSUE TITLE
Launchpad cannot turn pages with the scroll wheel [bug]

### ISSUE THREAD

**Issue by 906836920** [noah-nuebling/Mac-Mouse-Fix#420]
## Description

Launchpad cannot turn pages with the scroll wheel when enable Smooth Scrolling

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0 Beta 4
macOS Version: macOS 13 RC2
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey, thanks for your feedback! 

I think this is the same problem as #413. That problem should be fixed in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5).

If 3.0.0 Beta 5 still doesn't work for you, please open a new issue or let me know so I can reopen this issue.

Thanks!
