### ISSUE TITLE
Scrolling bug on Ventura [bug]

### ISSUE THREAD

**Issue by groverlynn** [noah-nuebling/Mac-Mouse-Fix#425]
Turning on smooth scrolling actually disables mouse scrolling on Ventura

**Comment by eatyourbaby** [comment]
I think this is the same as #413? I've been using `HEAD` for a few days and it's been fixed.

**Comment by noah-nuebling** [comment]
Hi @groverlynn thanks for your bug report! 

Your problem should be fixed in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5)! 
I think @DingoBits is right that this is the same problem as #413.

If you still experience the problem under 3.0.0 Beta 5, please open a new issue or let me know so I can re-open this one. Thank you!
