### ISSUE TITLE
Scroll wheel doesn't scroll in Citrix Workspace [bug]

### ISSUE THREAD

**Issue by spencercharris** [noah-nuebling/Mac-Mouse-Fix#427]
## Description

The middle button (scroll wheel) doesn't scroll in Citrix Workspace (version 22.10.0) When clicked/depressed, the button does transmit a middle click. It worked with Mac Mouse Fix 2.2.2, but when I installed macOS Ventura (13.0 build 22A380) MMF 2.2.2 stopped working so I got on the beta train (3.0.0 beta 4) that's when the scrolling stopped. 

## Context

Mac Mouse Fix Version: 3.0.0 Beta 4
macOS Version: 13.0 build 22A380
Mouse Model: Logitech M705

**Comment by spencercharris** [comment]
If I uncheck "Scrolling" from the menu bar "Enable for..." menu, the mouse wheel works again in Citrix Workspace. So it seems a per app enable/disable feature would mitigate the issue.

**Comment by noah-nuebling** [comment]
Hi, thanks for your feedback! 

Your problem should be fixed in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5)! I think it's the same one as #413.

If you still experience this problem under 3.0.0 Beta 5, please open a new issue or let me know so I can reopen this one.

Thanks!

**Comment by spencercharris** [comment]
Confirmed that Beta 5 resolves the issue - thanks!
