### ISSUE TITLE
with the new beta, scrolling doesn't work in some windows [bug]

### ISSUE THREAD

**Issue by cozyconner** [noah-nuebling/Mac-Mouse-Fix#433]
## Description

mouse scrolling doesn't work in certain windows

## Steps to reproduce

i used logic pro x
scrolling works in logic pro x
when i open up a 3rd party window like melodyne (perhaps window in window is the bug)
i can't scroll at all in melodyne
if i disable scrolling from mac mouse fix
it works

## Context

Mac Mouse Fix Version: 3.0.0 Beta 4
macOS Version: Monterey 12.6
Mouse Model: logitech ergonomic mouse

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey, thanks for reaching out! 

I think this is the same problem as #413. That problem should be fixed in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5).

If you're still having the same problems under 3.0.0 Beta 5, please open a new issue or let me know so I can reopen this one.

Thanks!
