### ISSUE TITLE
Scroll wheel scrolls up and down in Apple Maps.app, not zooms in and out [bug]

### ISSUE THREAD

**Issue by spencercharris** [noah-nuebling/Mac-Mouse-Fix#436]
## Description

When using the scroll wheel in Apple Maps, the map scrolls up and down when the expected behavior is zooming in and out. When I disable "Scrolling" in the menu bar icon's "Enable for..." menu, the scroll wheel reverts to the expected behavior.

## Context

Mac Mouse Fix Version: 3.0.0 Beta 5
macOS Version: Ventura (13.0 build 22A380)
Mouse Model: Logitech M705

**Comment by noah-nuebling** [comment]
Thanks for your feedback! 

This behaviour is because Maps will think you're scrolling on a Trackpad or a Magic Mouse when you use Mac Mouse Fix' Smooth Scrolling.

You should still be able to zoom in Maps using the "Zoom In or Out" feature in MMF. This feature simulates pinch to zoom on an Apple Trackpad. By default it's mapped to holding Mouse Button 5 and scrolling or holding Command (⌘) and scrolling.

You should also be able to zoom by holding Shift and scrolling. That's because holding shift will make Maps zoom when it receives Trackpad / Magic Mouse / Mac Mouse Fix scrolling input.

Hope that makes sense!

If you don't think this is ideal let me know and I will consider changing things.

**Comment by spencercharris** [comment]
Thanks Noah; I'll give it a try. (I have switched it from Mouse Button 5 to Mouse Button 4 as the closer placement of 4 makes it more ergonomic to simultaneously scroll.) Thanks!
