### ISSUE TITLE
MMF 3.0.0 beta 5 can't be enabled on ventura [bug]

### ISSUE THREAD

**Issue by MSamiulHasnat** [noah-nuebling/Mac-Mouse-Fix#441]
<img width="1440" alt="Screenshot 2022-11-08 at 9 24 30 AM" src="https://user-images.githubusercontent.com/58338543/200467968-dc81a397-aeda-4a72-adcf-3ab86bfff527.png">
## Description

In version 3.0.0 beta 5 MMF can't be enabled.

## Steps to reproduce

1. Deleted previously installed version of MMF.
2. Empty the trash.
3. find out the rest of the MMF file using the spotlight.
4. Cleaned leftover files using the cleanmymac.
5. Downloaded the MMF release zip from GitHub.
6. Installed and faced the issue of enabling.

## Context

Mac Mouse Fix Version: 3.0.0 Beta 5
macOS Version: Ventura
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Have you tried restarting?

**Comment by MSamiulHasnat** [comment]
> Have you tried restarting?

I did

**Comment by noah-nuebling** [comment]
Hmm weird.

**Thoughts on what's going on**

So I'm guessing you saw the "Mac Mouse Fix can't be enabled because there's another version present on your computer" message.

When you delete MMF after seeing this message and then don't restart your computer it just won't enable at all without showing you any message. (Not the best UX I know but I don't think there's a way to make it better) This is because the old version of Mac Mouse Fix is still registered in macOS and when you click enable it still tries to enable this old version - which won't exist on your computer anymore at this point. 

That's the only thing I know of which has the same symptomps that you experienced. But it should be fixed once you uninstall MMF and restart the computer. 

**Next steps**

If you send me more Logs that might help us figure this out.

Try recording logs of when you try to enable Mac Mouse Fix again. There should be one of these two messages in the Console:

- `Failed to register Helper with error:`
- `Registered Helper!`

If you send those messages and the ones surrouding them to me that should be very interesting.

Let me know if you have any more questions!

**Comment by carlfriedrich** [comment]
I can't enable MMF 2 since updating to Ventura as well.

This is my log when clicking on "Enable Mac Mouse Fix":

<img width="1735" alt="Bildschirm­foto 2022-11-17 um 12 46 40" src="https://user-images.githubusercontent.com/45259958/202438360-1cde0a3a-378a-4cd8-bbf8-92acff598901.png">

**Comment by noah-nuebling** [comment]
Hey @carlfriedrich, thanks for reaching out!
From those logs it looks like you might be using Mac Mouse Fix 2.2.0 or below. I only added Ventura compatibility in 2.2.1. 

So if you download the latest [2.2.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.3) that might fix your issues.

Let me know if that works or if you have more questions!

**Comment by carlfriedrich** [comment]
@noah-nuebling Ah, I didn't realize there was a new release. That indeed fixes my issue. Sorry for the noise and thanks for the quick reply!

**Comment by noah-nuebling** [comment]
No worries at all, glad to help! :)

**Comment by noah-nuebling** [comment]
Hey guys I'll close this now assuming it's been resolved. Let me know if you still have issues.
