### ISSUE TITLE
Mouse had issues, rebooting helped - FIXED [bug]

### ISSUE THREAD

**Issue by JJ00899** [noah-nuebling/Mac-Mouse-Fix#454]
## Description

I have a Kensington Wireless Trackball (K75326WW)

I installed MMF and it was working fine. 5 minutes later, my mouse is dead.
Will NOT work on any other computer, cursor will not move either.

Is there a fix for this? Please tell me as I am not trying to buy another $80 mouse.

## Steps to reproduce

1. Installed MMF
2. Tested out the custom buttons.
3. Added more buttons from my mouse to customize.
4. Tested them out to see if they worked.
5. All was fine for 5 minutes then everything stopped working - mouse is not even recognized, cant move cursor. wtf?

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Monterey 12.6
Mouse Model: Kensington Wireless Trackball (K75326WW)

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @JJ00899, sorry about your mouse!
Of course I can't be entirely sure, but I've never heard of a mouse being killed by Mac Mouse Fix and based on my technical understanding of how Mac Mouse Fix works, I don't think that it would be possible.

If you find out more or if anyone else has this problem please do let me know though!

**Comment by JJ00899** [comment]
Not sure what else it could be, the fact that it stopped working within 5 minutes of the install only can direct to the software. I have a similar mouse (bluetooth) that currently works fine.

**Comment by noah-nuebling** [comment]
To elaborate, I don't think it would be possible for Mac Mouse Fix to fry a mouse, because it doesn't send any information to your mouse. It just uses Apple's APIs to get information and input from your mouse. 

And the only way that I can think of how a program could fry a mouse is if it sends some data to it that affect the mouse's state such that it doesn't work anymore.

I'm not 100% sure, but I actually think that macOS would be reading and monitoring **all** of this information even if Mac Mouse Fix wasn't running. So I think that the actual information that is being sent between the computer and the mouse isn't affected by Mac Mouse Fix whatsoever.

Again, I cannot be 100% sure, but I think it's **very** unlikely that Mac Mouse Fix fried your mouse.

But of course I understand if you're wary now because of your experience. If you don't want to use Mac Mouse Fix anymore, I recommend [SteerMouse](https://plentycom.jp/en/steermouse/) or [LinearMouse](https://linearmouse.org/).

Hope that works for you, sorry again about your mouse! And do let me know if you  have any more info or questions.

**Comment by noah-nuebling** [comment]
> Not sure what else it could be, the fact that it stopped working within 5 minutes of the install only can direct to the software. I have a similar mouse (bluetooth) that currently works fine.

I think the most likely explanation is that you installing Mac Mouse Fix and your mouse dying within a short timeframe was a coincidence. I've never had that happen, but I guess mice "just die" sometimes.

**Comment by JJ00899** [comment]
Thanks for the response but, ha, I cant accept that a 5 minute timeframe between install MMF and my mouse completely dying is a coincidence. Been working fine since I got it. Has anyone experienced this or am I one in a milli?

**Comment by noah-nuebling** [comment]
I understand. No one has ever reached out to me about such an issue. But again, I get it if you don't feel comfortable anymore using Mac Mouse Fix now. 

Here is a list of some popular alternatives: https://alternativeto.net/software/mac-mouse-fix/

Let me know if I can do anything else.

**Comment by JJ00899** [comment]
With your knowledge, is there anyway for me to diagnose the issue? I can see that the dongle is recognized by my MAC, but that is all.

**Comment by noah-nuebling** [comment]
Hmm I don't know too much about hardware unfortunately.

The only thing I can think of to analyze the problem is you could use `IORegistryExplorer` to see if your mouse is still recognized by the system in any way. If yes, I guess that would tell you that your mouse is still working well enough to communicate its existence to the computer but not well enough to send input reports about button presses or scrolls. I don't know how that would help though, and learning what's going on in the `IORegistryExplorer` would probably take a bit of time. So I honestly don't think that's worth it.

Maybe Kensington support can help or you could ask on some forum like this one: https://forums.macrumors.com/forums/mac-accessories.77/

**Comment by mhy-beta** [comment]
I had a similar situation, I want to add without opening a new topic.

I installed "Mac Mouse Fix", it worked for 5-10 minutes and all of a sudden the mouse stopped moving. I thought the system was locked. I pressed keys on the keyboard but there was no response either. Then I saw that only the F1-F2 keys work from the keyboard.

Then I left the computer for about 10 minutes, when I returned the mouse was moving but not "clicking". It hits the "x" button to close the window but doesn't "click".

I manually rebooted the system.

My mouse is A4Tech G10-810F

**Comment by JJ00899** [comment]
> I had a similar situation, I want to add without opening a new topic.
> 
> I installed "Mac Mouse Fix", it worked for 5-10 minutes and all of a sudden the mouse stopped moving. I thought the system was locked. I pressed keys on the keyboard but there was no response either. Then I saw that only the F1-F2 keys work from the keyboard.
> 
> Then I left the computer for about 10 minutes, when I returned the mouse was moving but not "clicking". It hits the "x" button to close the window but doesn't "click".
> 
> I manually rebooted the system.
> 
> My mouse is A4Tech G10-810F

Interesting. Yeah mine still wont work. Tried on 2 other computers, MAC and Windows - nothing. MAC does recognize dongle but thats it's. Frustrating that its like a one and done situation it seems. Retarted / rebooted system as well. Thankfully I have a backup, but if Kensington cant help, Ill need to purchase a new one.

**Comment by noah-nuebling** [comment]
Hi @mhy-beta! That sounds kind of like the symptoms that happen when you turn off the Accessibility Access for "Mac Mouse Fix Helper" while the app is enabled. Do you think that might have happened?

The person in #443 also had this issue.

**Comment by noah-nuebling** [comment]
As far as I know it's a bug on Apple's side that I unfortunately can't do anything about.

**Comment by JJ00899** [comment]
Ok, it works now after resetting my computer multiple times and keeping it unplugged for a bit. We can close this thread!

**Comment by noah-nuebling** [comment]
Nice! Congratulations! that must be a relief :)

**Comment by JJ00899** [comment]
> Nice! Congratulations! that must be a relief :)

Yes, and thank you for your help. I've retitled issue so it wasnt so negative haha!

**Comment by mhy-beta** [comment]
I'll look there too but I didn't turn off the access permission. I was even thinking why I can't see the app in "applications". He didn't move while looking for it.
@JJ00899 I'm glad for you, I hope you continue to use it without any problems.

**Comment by noah-nuebling** [comment]
> > Nice! Congratulations! that must be a relief :)
> 
> Yes, and thank you for your help. I've retitled issue so it wasnt so negative haha!

Well thank you for that!

**Comment by noah-nuebling** [comment]
> I'll look there too but I didn't turn off the access permission. I was even thinking why I can't see the app in "applications". He didn't move while looking for it.
> @JJ00899 I'm glad for you, I hope you continue to use it without any problems.

Sorry my reading comprehension isn't the greatest sometimes, are you saying the app disappeared from the applications folder when your computer froze?

**Comment by mhy-beta** [comment]
@noah-nuebling Yes I couldn't find "Mac Mouse Fix" in the applications folder. I will soon boot Ventura instead of windows11 and check again.
I'm new to Hackintosh and I'm trying to fully understand what's going on.

I'll let you know if I can't find it or if there is any other problem.
Thank you for your interest.

**Comment by noah-nuebling** [comment]
> I'll let you know if I can't find it or if there is any other problem.

Ok sounds good. Thank you.

**Comment by mhy-beta** [comment]
Hi @noah-nuebling , I'm booting Ventura and find "Mac Mouse Fix", but not found Apps folder and System Informations->Apps. I run again "Mac Mouse Fix.app", opened app. But not work middle button and 4th and 5th buttons.
I'm added screenshot.
![macmousefix-screenshot](https://user-images.githubusercontent.com/76412344/204057727-51f78dfd-b007-4975-8186-e00f8ce6b898.png)

**Comment by noah-nuebling** [comment]
Hey @mhy-beta, sorry for the late reply. If you Click the Mac Mouse Fix Icon in the Dock while holding the "Command" modifier, that will reveal the app in the file explorer. Then you can move it into the applications folder. 

The fact that your buttons don't work is strange. I would assume it's due to some bugs in Ventura or your hackintosh installation. 

I made some changes to how inputs are processed in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5) which might fix your issue. Let me know how it goes!
