### ISSUE TITLE
Microsoft Precision Mouse troubles

### ISSUE THREAD

**Issue by andrewt82** [noah-nuebling/mac-mouse-fix#49]
Noticed an issue with Microsoft Precision Mouse

After installing Mouse Fix (0.9.1), a problem appeared, the middle of the side buttons stopped working, which switched programs like Cmd  + Tab

Can I fix this somehow?

![Screenshot 2020-10-06 at 12 23 31](https://user-images.githubusercontent.com/15378087/95183832-33959d80-07cf-11eb-92f2-d0ffebe85311.png)

**Comment by noah-nuebling** [comment]
Hi there Andrew, thank you for your feedback! 
Unfortunately I don't know why this button wouldn't work with Mac Mouse Fix, and I currently have no way of finding out, because I don't have such a mouse. This issue is definitely noted, but I can't promise anything when it comes to fixing it unfortunately.

You might wanna check out some alternatives to Mac Mouse Fix like [Steer Mouse](http://plentycom.jp/en/steermouse/) though, it has great compatibly with all sorts of mice. Other great alternatives are ControllerMate, USBOverdrive, and BetterTouchTool.
