### ISSUE TITLE
MouseFix Nonfunctional on M1 Mac [other]

### ISSUE THREAD

**Issue by adamndc** [noah-nuebling/mac-mouse-fix#52]
Recently purchased a new M1 Mac and mouse fix is completely nonfunctional. In System Preferences, I am unable to open up the preferences pane or access the software in anyway.

**Comment by ohserezha** [comment]
AFAIK that is not because of M1 but Big Sur update

**Comment by kode54** [comment]
Correct, it's also broken on Intel on Big Sur, because it's not notarized.

If you have your own Developer ID Application certificate, or the author himself can follow along, and sign it from a terminal, submit for notarization, and staple the prefPane bundle once that is accepted.

```
codesign -s "Developer ID Application" --force --options runtime Mouse\ Fix.prefPane/Contents/Library/LaunchServices/Mouse\ Fix\ Updater # this needs re-signing separately, because --deep doesn't know to sign it
codesign -s "Developer ID Application" --force --options runtime --deep Mouse\ Fix.prefPane
ditto -c -k --sequesterRsrc --keepParent --zlibCompressionLevel 9 Mouse\ Fix.prefPane Mac-Mouse-Fix-version.zip
xcrun altool --notarize-app --primary-bundle-id "com.nuebling.mousefix" --username "youricloudaccount" --password "@keychain:somekeychainitem" --asc-provider yourdevaccountidcode --file Mac-Mouse-Fix-version.zip
# await authorization here
# assuming that passes
xcrun stapler staple Mouse\ Fix.prefPane
ditto -c -k --sequesterRsrc --keepParent --zlibCompressionLevel 9 Mouse\ Fix.prefPane Mac-Mouse-Fix-release.zip
```


Naturally, Xcode can do all of this automatically with the Archive pass, but you have to turn on hardened runtime (the thing that `--options runtime` does above) and submit it for developer id notarization.

**Comment by kode54** [comment]
Here, since this hasn't been tended to yet, I assume the author is somewhat busy with real life issues, or other software, or who knows? Anyway, I don't think my friend whose team I'm in will mind terribly much if I toss this up for now. Feel free to test it on an M1, but it's going to be running under Rosetta 2, so I don't know how well it will work, if at all.

[Mac-Mouse-Fix-0.9.2-Beta-5.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/5656740/Mac-Mouse-Fix-0.9.2-Beta-5.zip) - Notarized by Resolute, Ltd. You should find the executable portions of all the binaries are 100% identical to the GitHub release, just a new signature. Same Developer ID I'm currently using for Cog.

**Comment by adamndc** [comment]
@kode54 Thanks! Installed and it seems to be working fine under Rosetta 2 for now.

**Comment by noah-nuebling** [comment]
Hey @kode54, thanks so much for contributing and helping out! 

@ADelCastillo1798 Does the new 1.0.0 release work on M1 your M1 machine?

**Comment by therain7** [comment]
@noah-nuebling works for me on my M1 MacBook Air. Runs through Rosetta, though. Can we expect universal binary?)

**Comment by noah-nuebling** [comment]
I've heard about stutter scrolling when using MOS on M1, have you noticed anything?

**Comment by therain7** [comment]
@noah-nuebling if u're talking about this app (https://mos.caldis.me), then, well, I didn't try it. 
Your app works fine for me

**Comment by noah-nuebling** [comment]
Awesome, good to hear that it's all working well for you on M1.
I had some dependencies causing trouble building natively for arm, but I just figured it out! [1.0.1 Beta 2](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/1.0.1-Beta-2) should run natively on your Machine.

**Comment by therain7** [comment]
Working fine natively on my MBA. Thank you)

**Comment by noah-nuebling** [comment]
Sure thing :)
