### ISSUE TITLE
Cannot enable Mac Mouse Fix on Ventura [bug]

### ISSUE THREAD

**Issue by mgoyanes** [noah-nuebling/Mac-Mouse-Fix#549]
## Description

Hi.

can not enable Mac Mouse Fix.

Although it shows as enabled, it does not work.
I then removed Mac Mouse Fix Login Helper and added it again, but without success.

If I do  sudo launchctl bootstrap gui/$UID ~/Library/LaunchAgents/com.nuebling.mac-mouse-fix.helper.plist I get /Library/LaunchAgents/com.nuebling.mac-mouse-fix.helper.plist: No such file or directory
Bootstrap failed: 2: No such file or directory

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Ventura 13.2.1
Mouse Model: MX Master 3 for Mac

## Additional Comments

–

---

### Console Logs

https://pastebin.com/WPw66g9j

### Crash Reports

–
<img width="458" alt="Screenshot 2023-04-01 at 14 28 53" src="https://user-images.githubusercontent.com/5049948/229292557-1c4d57e8-16e0-46d4-b8b7-0d4374797b2f.png">

<img width="458" alt="Screenshot 2023-04-01 at 14 29 11" src="https://user-images.githubusercontent.com/5049948/229292567-033586a7-6f74-480e-84be-3e3b616698e3.png">

<img width="723" alt="Screenshot 2023-04-01 at 14 31 58" src="https://user-images.githubusercontent.com/5049948/229292570-4b75ec8c-2ee7-440a-b02a-1598aa809d48.png">
<img width="1343" alt="Screenshot 2023-04-01 at 14 29 46" src="https://user-images.githubusercontent.com/5049948/229292574-11479b39-4a2e-4de6-8e5b-0edb818c6b77.png">
<img width="576" alt="Screenshot 2023-04-01 at 14 29 29" src="https://user-images.githubusercontent.com/5049948/229292578-610af268-178e-410f-a822-12d275f2fd8d.png">

**Comment by noah-nuebling** [comment]
Hey @mgoyanes,

Thanks for your detailed report and I'm sorry for the late reply!

There are troubleshooting steps in issue https://github.com/noah-nuebling/mac-mouse-fix/issues/648. 
If you try the steps there and let me know how it goes that would be super helpful. Thanks!

I'll close this issue now to move all the conversion around the problem to #648.

---

More detailed thoughts on what you sent:

The `There is no application set to open the URL` popups are very interesting. It kind of looks like macOS is trying to run the 'Mac Mouse Fix Helper' background task of a Mac Mouse Fix 3 copy, but the URL opening system can't find Mac Mouse Fix 3.

That's very weird. Did you install Mac Mouse Fix 3 and then move it to the trash by any chance? That might explain this. Some user had very similar issues and it turned out Mac Mouse Fix 3 was in some hidden dropbox cache folder and macOS was still trying to run that when clicking 'Enable Mac Mouse Fix'. Something like that might also explain the errors you're seeing.

I also took a brief look at your logs and it looks like the macOS api for running background tasks just says that it successfully started the 'Mac Mouse Fix Helper' which is a lie. But it always says that for people with this issue, so it's not surprise. 

But either way, I think the best course of action is to try the steps in #648.\
Especially the step with the `launchctl print` terminal command would be very interesting.

Thank you!
