### ISSUE TITLE
Overrides Global Modifier Keys [bug]

### ISSUE THREAD

**Issue by odonckers** [noah-nuebling/Mac-Mouse-Fix#566]
## Description

After removing all of the modifier keys, I want to use "Shift", "Option", "Command", and "FN" for Swish. I'd like to use those keys for Swish.

## Steps to reproduce

1. Remove all modifier keys from the settings menu.
2. Using Swish, attempt to hold "Shift" and then swipe up using one of the Mouse Fix modifiers.

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: 13.3.1
Mouse Model: Logitech MX Master 3s

## Additional Comments

Thank you so much for any help you can provide!

---

### Console Logs

–

### Crash Reports

–

**Comment by vjraitila** [comment]
I'm also an avid user of https://highlyopinionated.co/swish/ for managing windows with trackpad gestures and was looking for an app to complement it when reaching for a mouse instead. Mac Mouse Fix looked promising as it can convert 3rd party mouse interactions into gestures in addition to fixing scrolling.

But immediately ran into the same problem as you.

Gestures holding down a modifier are important to me as e.g. in Swish by holding down the shift key enables snapping the window into thirds instead of halves. This is essential using wide screens.

MMF seems to hijack the modifier activation in a way that Swish does not receive it when swiping.

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: 14.1.2
Mouse Model: Logitech G502 X LIGHTSPEED

**Comment by noah-nuebling** [comment]
Hey there guys, thanks for reaching out. 

I'm also using Swish with modifiers, and for me it seems to work fine. Can you guys provide more details about the specific scenario where things don't work? Maybe a screen recording would be helpful. Thank you.

**Comment by vjraitila** [comment]
I'll see about the recording a bit later. But here's what I do:

STEPS TO REPRODUCE

1. Set middle mouse button Click & Drag action to Scroll & Navigate in MMF
2. Hold down the shift key
3. "Swipe" a window titlebar left in order to snap it to the first third of the screen

EXPECTED RESULTS

Swish changes to the mode snapping to thirds and two-thirds and I'm able to select the first third.

ACTUAL RESULTS

Swish is stuck only snapping to left and right halves of the screen.

I am able to select thirds, but only _if_ I reverse the order and start swiping first and after that press down the shift key.

**Comment by noah-nuebling** [comment]
Hey @vjraitila, thanks for getting back. I was able to reproduce this with your instructions. I hadn't been using any modifiers with Swish, except Command-Shift as the super modifier. And that worked fine with Mac Mouse Fix. So some modifiers seem to work and others don't, which is a little weird. I'm focused on publishing version 3 at the moment but I'll try to look into this at some point. If you find out anything more regarding in which scenarios things work and in which scenarios things break down, it might also be helpful to let me know since it can give hints as to what's going on. You might also want to contact the dev of Swish about this, since maybe the bug is on their end.


> I am able to select thirds, but only if I reverse the order and start swiping first and after that press down the shift key.

This is also interesting. I'm not sure what this means but my feeling based on this is that the problem is on the side of Swish.


I hope this helps a little or at least makes things more clear.

**Comment by vjraitila** [comment]
Thanks, I contacted the Swish developer as well. 

I freely admit that I have no clue where the root cause lies. However, contrary to your intuition, the behaviour you highlighted indicates the opposite to me. Like the held down modifier along with the gesture event is somehow first caught and handled by MMF, not propagated down the chain and hence no longer received by Swish. And only after I repeat the key press, it gets through.

That fact that only some modifiers are affected, however, is arguably strange.

**Comment by noah-nuebling** [comment]
Ok cool, maybe the Swish dev can figure something out. Regarding your intuition, that's interesting - thanks for sharing! I don't think it's what's happening, since Mac Mouse Fix doesn't actively intercept modifier events in most scenarios. You can check if it's intercepting modifiers for you by going to 'Activity Monitor.app' and seeing if 'Mac Mouse Fix Helper' uses any CPU when you press and release modifier keys on your keyboard.

If you have any more thoughts or ideas feel free to let me know! I don't know what's going on either so any ideas are appreciated.

**Comment by chrenn** [comment]
Good news, I figured it out.

For some reason, touch events emitted by Mac Mouse Fix include an NS/CGEvent ModifierFlag with a rawValue of 536870912, which is a) completely undocumented, and b) not removed via OptionSet intersection with the `.deviceIndependentFlagsMask`. This threw off the regular modifier detection but not the super modifier, since it is handled separately inside Swish. A fix will be out with the next update.

Thanks for reporting and investigating this!

**Comment by noah-nuebling** [comment]
Oh hey Chris, thanks for looking into it! Great that you figured it out! I ran into this stuff too when dealing with modifiers. I think it's an error on Apple's end. I ended up using the mask `0xFF0000` instead of `.deviceIndependentFlagsMask` (which is `0xFFFF0000`), and that fixed all such issues in my code.

I hope that helps, and happy coding!

**Comment by vjraitila** [comment]
@chrenn Any news regarding getting this fixed? The issue is still making MMF and Swish, while great apps in their own right, work sub-optimally together. Especially with wide screens where thirds are more heavily leveraged.

**Comment by chrenn** [comment]
@vjraitila Sorry for the delay! I've been working on Swish 2 (paid upgrade coming later this year), but I'll push an update for Swish 1 before Sequoia releases.
