### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by jcbvm** [noah-nuebling/Mac-Mouse-Fix#625]
I don’t see much activity the last couple of months, is this project dead?

**Comment by 906836920** [comment]
I THINK SO ,AND I JUST PURCHASED A GENUINE VERIFICATION, SO SAD @noah-nuebling @noahmtnr

**Comment by michaelweinold** [comment]
It seems that @noah-nuebling is still actively contributing to the development branches of the repo. Perhaps he could provide an update on the state of the project? The last beta release of [3.0.0 Beta 6](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-6) is now over half a year ago.

**Comment by janzen0816** [comment]
I seem to remember that the author said that he was still in school and was busy with his studies, so he had no time to update. I hope he can return to normal update as soon as possible.

**Comment by 906836920** [comment]
If so, hope so

janzen0816 ***@***.***> 於 2023年8月24日週四 下午11:24寫道：

**Comment by noah-nuebling** [comment]
Hey guys, I'm really sorry about the lack of updates. I've been having a difficult time emotionally. But I'm working on a new website for the 3.0.0 update at the moment and hope to release it soon and I think it will be really great.

I will also do my best that everything works nicely for the next macOS update before that comes out. I'm fairly confident that I'll be able to do this, but I don't want to promise anything at the moment.

I definitely have lots of cool features planned for the app that I would love to build and release. I think I could make MMF the definitive mouse driver for Macs if I can realize these plans. But unfortunately I can't give a schedule for how long that will take or how much time I will end up spending on the project because I'm not very mentally stable at the moment.

Sorry to anyone who purchased the app during the beta expecting better support for it. I also expected to be able to support it better. Now I'm wondering if it's okay for me to sell an app under these circumstances. Maybe I could put a disclaimer somewhere? If you guys have any input on this I'd be eager to hear it. Thanks.

**Comment by 906836920** [comment]
> 

It's ok, we are just curious why it has not been updated for a long time. I am sorry to hear that you are currently in a bad situation. You just need to follow your rhythm. I hope you can recover soon. <hug>

**Comment by noah-nuebling** [comment]
> I THINK SO ,AND I JUST PURCHASED A GENUINE VERIFICATION, SO SAD @noah-nuebling @noahmtnr

Hey Kevin @906836920, I hope you don't feel frustrated about this, if you shoot me an email I can refund your purchase. And thanks for the kind words :)

**Comment by 906836920** [comment]
> > I THINK SO ,AND I JUST PURCHASED A GENUINE VERIFICATION, SO SAD @noah-nuebling @noahmtnr
> 
> Hey Kevin @906836920, I hope you don't feel frustrated about this, if you shoot me an email I can refund your purchase. And thanks for the kind words :)

it's ok, and I will wait till your release version, I'm sorry I don't understand your situation, I hope you can get well soon. and thanks all of your contribution to make Mac mouse better . everything will be ok :)

**Comment by noah-nuebling** [comment]
Thanks a lot, that's very nice to hear for real :)

**Comment by noah-nuebling** [comment]
Thanks a lot man that feels good to read :)

I deleted the GitHub message saying the same thing because I felt weird saying this publicly. But thank you.

**Comment by 906836920** [comment]
> 

ok

**Comment by ib0ndar** [comment]
Noah, in these difficult times for you let me thank you for your tremendous work. I hope you will get back on track soon leaving behind all the difficulties you are experiencing right now. Your product is the best and really stands out, I really enjoy the 3.0 beta and thank you every time I do a zoom with Cmd+Mouse wheel :))))) Only because of your great software I could return back that awful Apple Magic Mouse and keep using my trustworthy Logitech mouse with my new Mac :))) Please, keep your great work! Thank you again!

**Comment by michaelweinold** [comment]
Hey @noah-nuebling - the project, even as is stands now, is a huge achievement. The feature set is, by my estimate, the most complete of all contenders. But aside from that, your own mental health should always take priority. I hope you'll be back on your feet soon - all the best!

**Comment by S-n-d** [comment]
Hey @noah-nuebling just chiming in to say how grateful I am of your work. You make using a non-apple mouse on macOS bearable 😉 Thanks for all the hard work, and I hope you will get back to a healthy state of mind! Much love

**Comment by riasat-sheikh** [comment]
>  and thank you every time I do a zoom with Cmd+Mouse wheel :)))))

This is not working in macOS 14 (at least for me). So, be careful when updating your OS since, macOS 14 is going to be released soon.

**Comment by noah-nuebling** [comment]
Thanks so much for the feedbacka nd encouragement guys! I'll close this now to clean the issues up a little and hopefully I can release version 3.0.0 soon.
