### ISSUE TITLE
How can I disable Cmd + scroll override from Mac Mouse Fix for all? [enhancement]

### ISSUE THREAD

**Issue by keikhcheung** [noah-nuebling/mac-mouse-fix#63]
Hi,

I love using Mac Mouse Fix for the configuring extra buttons on my external mouse. It has been very helpful.
I have been using, as well, another mouse config app ([Mos](https://mos.caldis.me/)) for smoother scrolling (with scroll inertia), configurable keys for horizontal scroll and dash scroll. I have maintained the smooth scroll on Mac Mouse Fix _off_.

When Mac Mouse Fix was a System Preferences pane, they have worked perfectly together. Mac Mouse Fix would manage the extra mouse buttons; Mos for scrolling.
However, since the latest update, which changed to an app, Cmd + scroll has always been taken over by Mac Mouse Fix (resulting in non-smooth scrolling as I have the setting _off_ on MMF; turned _on_ in Mos). Normal scrolling still works with the smooth scrolling managed by Mos, though.

The only way I have so far found out to disable MMF’s Cmd + scroll intervention is to add specific apps in App-specific settings to exclude them one by one. Is there a way to just disable it for all?

Thanks a lot.

**Comment by noah-nuebling** [comment]
Hey there @keikhcheung thanks for your feedback!

I'm sorry I probably won't get around to implementing something like this any time soon.
Mac Mouse Fix isn't made to work at the same time with MOS or other mouse drivers. If I made that a priority it would be quite a big hassle, and stuff could break all the time whenever the other mouse drivers change something.

However, if turning off Command-Scroll for all apps, or turning off scrolling interception entirely, turns out to be a more common request, I'll consider implementing that. It would be possible to do this on the technical side, but I'm not sure how it would fit into the user interface.

In the mean time you might want to check out [SteerMouse](http://plentycom.jp/en/steermouse/index.html), wich is another great mouse driver that can also remap buttons like Mac Mouse Fix among many other things.

**Comment by noah-nuebling** [comment]
Hey @keikhcheung, you're making some good points here. 
I agree that it would be nice to be able to selectively turn off each part of the program entirely, so you can be sure that it's behaving exactly as it would without Mac Mouse Fix turned on and is not interfering with anything. 

Ideally I’d like users to not have to think about the fact that they’re using Mac Mouse Fix at all, and if it’s preventing the use of these options in Firefox, that’s clearly going against those ideals.

I'll try to provide this ability at some point in the future, but I don’t have too much time on my hands and it’s not at the top of the list of priorites right now, so please don't expect anything in this regard soon.

But anyways thanks again for your contribution and for sharing your point of view! You got me thinking about some things I hadn’t considered before.

**Comment by noah-nuebling** [comment]
Hey @keikhcheung,

Inertial scrolling and the ability to turn off Cmd-scroll is available in the latest latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

Hope you like it and let me know if you have more thoughts or issues!
