### ISSUE TITLE
Free day trial counter incorrect [bug]

### ISSUE THREAD

**Issue by Th3o4oR** [noah-nuebling/Mac-Mouse-Fix#644]
## Description

Just downloaded the app today, and the free day trial started at 1/90. Restarted my macbook, and now it shows day 3/90. 

## Steps to reproduce

Not sure how I would reproduce this...

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Sonoma 14.0
Mouse Model: MX Master 3S

**Comment by noah-nuebling** [comment]
Hey Theodor, thanks for reaching out!

Not sure why this could be as of now. But if you give me some more context that might help me figure it out. 

- Does the counter go further up when you restart the computer? 
- Was it around midnight when you installed the app / restarted your Mac?
- Is there anyting unusal about your iCloud setup or your keychain? Like are you logged into your computer with a normal Apple ID which has iCloud? Are you using the iCloud Keychain?

Not sure I can work on this very soon, but if you shoot me an email I might be able to help you in another way.

Hope that works for you and have a nice day!

**Comment by Th3o4oR** [comment]
Hey! Happy to help. I've restarted twice more since reporting the issue, but the counter has only gone up once, to 4/90. Not able to reproduce it. 

I didn't do this at midnight, I started the download in the evening, around 17/18. 

I am using iCloud keychain. I don't think there is anything unusual about it, at least that I know of. 

Let me know if there is anything else I can help with!

**Comment by janzen0816** [comment]
I've encountered the same issue.

**Comment by noah-nuebling** [comment]
@janzen0816 Do you remember the circumstances exactly the same as for @Th3o4oR? For example, did you also encounter it when you restarted the computer for the first time after installing the app? And did it also count up to 3 days?

Thanks!

**Comment by noah-nuebling** [comment]
@Th3o4oR Thanks!

**Comment by Th3o4oR** [comment]
Mine has crept up to 5/90 days, and I think I've performed two more restarts since installing. I checked after the second restart, and it still said 4/90, so it doesn't happen immediately after restart. Keep in mind I'm using the public beta for Sonoma 14.0.I'll try to restart again and see if it increases to 6/90.

**Comment by noah-nuebling** [comment]
@janzen0816 @janzen0816 Did you guys have a stable internet connection when this happened? If the internet cut out or you had no internet connection that might have something to do with it.

This is because the number of days you've used the app are both stored in your iCloud keychain (which is synced over the interne), and also cached in a local file called config.plist. Maybe there were some conflicts there. 

If you have several different computers which are using the same iCloud keychain maybe that could also have something to do with it. I'm just spitballing here.

**Comment by Th3o4oR** [comment]
Just performed a restart, and same thing happened. Immediately after, the counter was still at 5/90, but a little while later it had jumped to 6/90. I have not noticed any issues with internet connectivity.

**Comment by janzen0816** [comment]
yes，I'm experiencing the exact same situation as he is. The number of days increases shortly after a restart. My system is macOS 12.6.

**Comment by noah-nuebling** [comment]
Okay I can reproduce it now. For me it actually happens everytime you use the mouse for the first time after disabling and reenabling MMF as well as after restarting the computer.

Can you guys confirm, that it also happens when you disable MMF and then re-enable it?

**Comment by janzen0816** [comment]
Yes, I confirm that the same thing happens when you disable it and then re-enable it. The same thing also occurs when uninstall and then reinstall it.

**Comment by noah-nuebling** [comment]
Ok great thanks for checking @janzen0816. It seems I can reproduce your exact issue so I don't need any further info from you for now. Thanks for your help! And if you'd like a free license, just shoot me an email.

**Comment by Th3o4oR** [comment]
After disabling and re-enabling MMF, my counter increased once, but there doesn't seem to be an 1:1 ratio between toggles of the button and increases of the counter.

**Comment by noah-nuebling** [comment]
Hey guys I think I fixed the problem in this this commit 9c4a8db12a2c0658e2aaf68f421882943c8aed88. But I don't know when I'm going to release this.

In the mean time, I think you can prevent this issue in the current 3.0.0 Beta 6 release by going to Mac Mouse Fix's configuration file called 'config.plist' and manually inserting some values. You can find the configuration file by going to the 'About' tab in MMF 3 and then clicking the Mac Mouse Fix icon while holding Command and Shift on your keyboard. This will reveal the 'config.plist' file in Finder. 

You can open and edit this file using Xcode, or with a plaintext editor.

In config.plist, create a Dictionary called 'trial' at Root > License, and then create a Date called 'lastUseDate' at Root > License > trial. I think the value for the date could be anything, but maybe you have to set it to some dummy value that's a valid date e.g. '2023-08-24T20:06:52Z'.

If you configured the config.plist file correctly, it should look like this in Xcode:

<img width="1411" alt="CleanShot 2023-08-24 at 22 22 19@2x" src="https://github.com/noah-nuebling/mac-mouse-fix/assets/40808343/0eb8e24f-7541-40bc-a077-e91ba57891cd">

Once you set it up like this, the trial counter should not incorrectly increase anymore.

If anybody's trial has run out because of this, please shoot me an email and I will provide you with a free license (I might be very slow to respond though, sorry)

I hope this helps, and let me know if you have any more questions.

**Comment by janzen0816** [comment]
Hi noah, I'm here. I'm glad you can give me a free license. My email address is "zhangzhaoid@gmail.com". I will delete this reply containing private information after receiving your free license. Thank you very much!

> Ok great thanks for checking @janzen0816. It seems I can reproduce your exact issue so I don't need any further info from you for now. Thanks for your help! And if you'd like a free license, just shoot me an email.

**Comment by noah-nuebling** [comment]
I'll close this now. Let me know if you still experience issues with this.
