### ISSUE TITLE
请问是否可以添加触摸板水平滚动翻转功能吗？ [enhancement]

### ISSUE THREAD

**Issue by WYS-Stack** [noah-nuebling/Mac-Mouse-Fix#646]
## Description
水平滚动反转

## Rationale
当鼠标和触摸板的垂直滚动反转已完全满足需要时，发现鼠标和触控板的水平滚动是相反的，使用起来很难受，所以可以添加一个水平滚动反转功能吗？

## Additional info
–

**Comment by janzen0816** [comment]
感觉放大缩小也需要翻转一下，不然是反直觉的

**Comment by noah-nuebling** [comment]
Hey guys, thanks for reaching out! Some issues with the click and drag direction have been resolved since 3.0.0 Beta 6 which I assume this Feedback is based on.

I'll close this now, assuming it has been resolved. 

If you still have problems you'd like to see addressed, please open a new issue. Thank you.
