### ISSUE TITLE
Add Mac Mouse Fix to Homebrew [enhancement]

### ISSUE THREAD

**Issue by arjpar** [noah-nuebling/mac-mouse-fix#651]
## Description
It would be useful to have this app available on homebrew so users could install from the terminal

## Rationale
It would ease the UX by a bit by allowing install from homebrew

## Additional info
None

**Comment by noah-nuebling** [comment]
Hey there @arjpar! 

You can use 

```
brew install mouse-fix
```

to install Mac Mouse Fix using Homebrew. 

I should probably advertise this in the readme, but I don't like that the formula is called `mouse-fix` instead of the proper name of the app `mac-mouse-fix`. I'll file an issue with them to change it if possible. Edit: Filed a [pull request](https://github.com/Homebrew/homebrew-cask/pull/154230).

**Comment by noah-nuebling** [comment]
The Homebrew formula has been updated!

You can now install Mac Mouse Fix through Homebrew with the Terminal command
```
brew install mac-mouse-fix
```
