### ISSUE TITLE
the forward and backward is not working with the app in the browser [bug]

### ISSUE THREAD

**Issue by omshejul** [noah-nuebling/Mac-Mouse-Fix#659]
## Description

the forward and backward is not working with the app in the browser but seem to work after quitting the app

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Version 13.5.2 (22G91)
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there @omshejul, thanks for your feedback. 

This sounds as if MMF might be interfering with some other mouse apps.

If your would still like to see this addressed, please open a new issue and let me know what browser you're using. You can link this issue instead of writing the description etc. again. Thank you.
