### ISSUE TITLE
Scrolling problems [other]

### ISSUE THREAD

**Issue by fredrofo** [noah-nuebling/mac-mouse-fix#66]
Hi

First of all, thank you for making this great app, which makes the mouse experience using a non-apple mouse awsome! After the newest update (with changing to app) i have som problems in scrolling through pdf-files. I am norwegian, so i am not shure what the name of the program is on english OS. Scrolling is totally fine on other programs, like safari, messages, etc. But when scrolling on pdf viewer (standard program) it is stuttery and wierd. 

Fredrik

**Comment by noah-nuebling** [comment]
Hey @fredrofo, thank you for reaching out, and for letting me know you like Mac Mouse Fix! :)

I think your issues likely stem from the fact that Smooth Scrolling is turned off by default for Apple's Preview app (The default pdf viewer). You can change this by checking the ‘Smooth Scrolling’ checkbox for Preview at 'Mac Mouse Fix' → 'More...' → 'App specific settings...'.

When using the 'Single Page' or 'Two Pages' view modes in Preview, scrolling is way too sensitive with Smooth Scrolling turned on, and you’ll scroll tens of pages at once from just a single scroll wheel tick. So I decided to turn Smooth Scrolling off for Preview by default.

It's possible to make smooth scrolling work with 'Single Page' and 'Two Pages' views in Preview by more closely emulating the scrolling events sent by an Apple trackpad and also sending touch events alongside. It's not so easy to do this though, so please don't hold your breath for any improvements in that respect in the near future.

I hope that helps or clears up things. If you have any more questions or thoughts, or you think your issues are due to something else let me know!

**Comment by fredrofo** [comment]
Ah perfect! That fixed it :) Thanks for quick reply

**Comment by noah-nuebling** [comment]
Sure thing, glad to help :)
