### ISSUE TITLE
Why this application is not working on macOS Sonoma?

### ISSUE THREAD

**Issue by MSamiulHasnat** [noah-nuebling/Mac-Mouse-Fix#688]
### Discussed in https://github.com/noah-nuebling/mac-mouse-fix/discussions/687

<div type='discussions-op-text'>

<sup>Originally posted by **MSamiulHasnat** October 18, 2023</sup>
Device - Mabook Air 2020 with 8GB of RAM
OS - macOS Sonoma
Application Version - Both v2 and v3
Mac Mouse Fix app is not running on my machine. It opens but doesn't enable.</div>

**Comment by Bat-Maniac** [comment]
@MSamiulHasnat,

I've got the same device (MacBook Air M1 2020 - macOS Sonoma) and Mac Mouse Fix (3.0.0 Beta 6) is working fine for me. Everything works as it should with a Logitech Pebble M350.
You have to enable Mac Mouse Fix in accessibility settings. Did you do that already?

**Comment by samchouse** [comment]
I'm in the same boat as the author, when I first downloaded this on Sonoma it worked decently with crashes when trying to open the app from the menu bar. Now it doesn't enable, I've given it permissions.

https://github.com/noah-nuebling/mac-mouse-fix/assets/46873232/577ad387-997a-40a5-b004-adafd28753e6

**Comment by noah-nuebling** [comment]
Hey there sorry for the late reply. I'm also on Sonoma and everything works perfectly for me. So I'm not sure what's going on.

You could try deleting all other versions of the app you might find on your computer, then empty the bin and then restart the computer. If that doesn't help, try filing a [Bug Report](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report) and attaching some console logs. That might help me fix the issue. Thank you.

**Comment by noah-nuebling** [comment]
Hi guys, sorry for the troubles, I'll close this now. Please open a new issue if you would like me to investigate this further.

Edit: I'm reopening this, because I saw there were more recent reports of this issue in the linked discussion #687.

**Comment by noah-nuebling** [comment]
Okay, to address this: I'm sorry about the troubles and the late reply! Does it help if you: 1. Close Mac Mouse Fix 2. Delete the file at `~/Library/Application Support/com.nuebling.mac-mouse-fix/config.plist` 3. Try again.

If that doesn't help you can try to file a [bug report](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report) and attach some console logs/crash reports.

Using [AppCleaner by freemacsoft](https://freemacsoft.net/appcleaner/) is the closest thing to get a 'clean uninstall' that I know of. This is necessary for a 'clean uninstall' because macOS creates tons of files in the library on behalf of Mac Mouse Fix that I don't even know about.

You can also check older issues in the [Can't Enable](https://github.com/noah-nuebling/mac-mouse-fix/labels/Can%27t%20Enable) category. Although some of those issues were from a time when the mechanism in macOS for running something in the background were different (It changed in macOS Ventura), so I think some of the solutions steps there aren't likely to help you guys.

Let me know if you find out anything more or if you have any questions. Oh and if anyone would like a **refund** over this, then just shoot me an email with 'refund' in the subject.

Update: 

I made a new category for enabling issues under Ventura and later: [Can't Enable](https://github.com/noah-nuebling/mac-mouse-fix/labels/Can%27t%20Enable%20Ventura%2B) (The enabling mechanism is fundamentally different for Ventura and later so any solution steps will also be different.)

**Comment by noah-nuebling** [comment]
Oh and also, one person in the related discussion (#687) mentioned that they tested other mouse apps, before Mac Mouse Fix stopped enabling. Did you guys do something similar by any chance? Or did you install or do something else around the time that Mac Mouse Fix stopped working? If you just share anything you can think of that might be helpful to identify the cause of this.

**Comment by noah-nuebling** [comment]
Another thing you could try is:

1. Delete any copies of Mac Mouse Fix on your computer
2. Empty the trash
3. Restart your computer
4. Try again

**Comment by noah-nuebling** [comment]
Hey guys,

There are more troubleshooting steps in issue https://github.com/noah-nuebling/mac-mouse-fix/issues/648. 
If you try the steps there and let me know how it goes that would be super helpful. Thanks!
The step with the `launchctl print` terminal command would be especially interesting.

I'll close this issue now to move all the conversion around the problem to #648.
