### ISSUE TITLE
Auto minimize [enhancement]

### ISSUE THREAD

**Issue by miloshev** [noah-nuebling/Mac-Mouse-Fix#692]
## Description
Hey there. I enjoy using this great little program, but everytime i start my computer i have to minimize the program window. Can you please make it, so it starts minimized?
Thank you very much and keep the good work :)

## Rationale
It is normal such utility programs to start minimized, as you dont need to do anything on the main window for it to work.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey there @miloshev, thank you for your feedback. 

Mac Mouse Fix doesn't normally open up when you start the computer. My guess is that you have added Mac Mouse Fix as a login item in your system settings. If you disable that and just quit Mac Mouse Fix, the enhancements for your mouse should still keep working. This behaviour will be made a bit more clear in version 3.0, since you're not the only one who's been confused by that. 

I hope that helps a little!

**Comment by miloshev** [comment]
Thank you! I will try this :) On 26 Oct 2023, at 18:18, Noah Nuebling ***@***.***> wrote:﻿
Hey there @miloshev, thank you for your feedback.
Mac Mouse Fix doesn't normally open up when you start the computer. My guess is that you have added Mac Mouse Fix as a login item in your settings. If you disable that and just quit Mac Mouse Fix the enhancements for your mouse should still keep working. This behaviour will be made a bit more clear in MMF 3 since you're not the only one who's been confused by that.
I hope that helps a little!
