### ISSUE TITLE
Progress on “Tilt Wheel as Buttons” [enhancement]

### ISSUE THREAD

**Issue by ed-ponce** [noah-nuebling/Mac-Mouse-Fix#713]
## Description
I’m not the only one who thought of mapping the wheel tilt “buttons” with Mac Mouse Fix. Is there any update or official statement regarding these requests?

## Rationale
I’ve been using Mac Mouse Fix to replace proprietary mouse software until now. I’m trying SteerMouse with my [Kensington Vertical Trackball](https://www.amazon.com/dp/B083L6B76T) but it’s not quite the same, to be frank.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey there @paruela, there's a statement on the new [Readme](https://github.com/noah-nuebling/mac-mouse-fix) under `Are tiltable scroll wheels supported? `. Does that clear things up?

**Comment by ed-ponce** [comment]
Yes it does! Thank you for your patience. I completely understand.

**Comment by ed-ponce** [comment]
For anyone interested: I ditched SteerMouse because of its $20 price tag. LinearMouse has helped me since. It’s free and open source and lets me map the scroll wheel tilt as buttons. The UX is not as neat and it lacks smooth scrolling, but gets the job done for my current setup.

Mac Mouse Fix is a product of a separate category and I’d like to come back to it.

**Comment by noah-nuebling** [comment]
Oh that's interesting that LinearMouse does that. Thanks for letting me know! Maybe that can help me implement something similar.

Edit: (This is just my stream of consciousness, it's not important) Okay I looked at the LinearMouse implementation. It seems to work by triggering actions whenever a scroll event comes in. This works nice for LinearMouse, but it won't work with the current button-remapping-implementation of Mac Mouse Fix, since it relies on having data about when a button is pressed **and** when it is released. This is only the case for button-events, not for the scroll events that the tilt-wheel sends. MMF uses this info about when a button is pressed and released to be able to assign many actions to the same button through different gestures, such as double click, click and hold, or click and drag. The whole implementation of the button-remapping system is based on having this data. So it probably wouldn't make sense to add tilt-wheel support on the 'Buttons' tab, (unless it's possible to reprogram the mouse to send button events when you tilt the wheel). However, this got me thinking, that maybe I could allow you to assign different actions such as 'Move Left a Space' to scrolling horizontally on the 'Scrolling' tab. I think that could be super nice. But it will probably be a lot of work and take me a long time to release, so please don't hold your breath. But either way thanks a lot for your input!

**Comment by ed-ponce** [comment]
I’m still hoping this is possible on a future update.

**Comment by ed-ponce** [comment]
The only thing keeping me from switching from SteerMouse+MOS to MacMouseFix is the lack of mappable buttons for scrollwheel tilts 🥲

Probably an unpopular request but given LinearMouse and SteerMouse have implemented this, I still want to believe.
