### ISSUE TITLE
Normal mouse middle click click not working anymore [bug]

### ISSUE THREAD

**Issue by DrJume** [noah-nuebling/mac-mouse-fix#73]
## Description

When using 'Mission Control & Spaces' for the mouse middle button other applications don't react to a normal mouse middle click anymore.

## Steps to reproduce

1. Set 'Click and Drag Middle Button' to 'Mission Control & Spaces'
2. Use Middle Button on a link in a browser
3. The link does not open in a new tab

## Context

Mac Mouse Fix Version: 2.0.0 Beta 1
macOS Version: 10.15.7
Mouse Model: –

## Additional Comments

It would be nice to let a single click through, and only after a drag should the action trigger/begin.

---

### Console Logs

–

### Crash Reports

–

**Comment by DrJume** [comment]
Btw, I really like the new TrackPad style drag hotkey! 🎉

**Comment by noah-nuebling** [comment]
Hey @DrJume, thanks for your feedback! 
The trackpad-style dragging has been a ton work but I'm really happy with how it turned out. I'm really glad you like it, too! :)

As for your issue, it is actually intended (if very unintuitive) behavior.
As soon as a button shows up on the left side of the list of remaps, it is 'captured' by Mac Mouse Fix and no other program can see when you click it.

To use the original function of middle click while the Middle Button is captured by Mac Mouse Fix:
1. Click the plus button under the list of remaps
2. Move the mouse pointer inside the field with the '+' in the middle
3. Click the Middle Button
4. Choose the 'Open Link in new Tab' option

This setup will make Mac Mouse Fix send simulated middle clicks when you click the middle button.

I know that this is super weird and unintuitive, but I've thought about this a lot and I think the 'capturing' of buttons, while not great, is the best solution. \
I'll try to have the app communicate what's happening and how to work around it some future Beta release.

Oh and btw if you or anyone else have any ideas or thoughts on how this could be communicated that'd be super appreciated! I'm still in the process of figuring this all out.

**Comment by DrJume** [comment]
Omg, I didn't even realise, that you now have so many possibilities for remapping! 🤦‍♂️ 

My suggestion would be to 
1. rename 'Open Link in new Tab' to 'Regular Middle Button Click' or something like that
2. activate a click mapping to this option by default when remapping the Middle Button
