### ISSUE TITLE
Add keyboard shortcut actions [enhancement]

### ISSUE THREAD

**Issue by DrJume** [noah-nuebling/mac-mouse-fix#74]
## Description
When setting a mapping for a mouse button, you have a keyboard shortcut option which can record a keyboard shortcut to be used

## Rationale
This feature could be used to map frequently used keyboard shortcuts to mouse buttons

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey @DrJume, I actually built that feature over the last few days, because of your request, and you can test it in [2.0.0 Beta 2](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

**Comment by DrJume** [comment]
Awesome 🎉 Thank you!

**Comment by DrJume** [comment]
It's working nice! I'm using it to activate Command+Tab for quick app switching.

I also wanted to try it out with Mosaic, a window manager which lets you drag a window onto an overlay *while pressing alt/option* to select window positioning/sizing presets to be applied to that window.

Sadly, I cannot set only **modifier key(s)** as keyboard shortcut action (to be held while I hold the mouse button) in Mac Mouse Fix. 

Could you add this please? I hope it is an easy adjustment to make for you. It would be great!

**Comment by noah-nuebling** [comment]
Wow I'm learning about a lot of cool apps because of you! I'll definitely try out Mosaic.

I hadn't thought of this use case, and I'll definitely take it into account for the future, but unfortunately, what you're asking for is not very easy to implement well, so I don't think I'll be able to build that feature very soon.

__If you are interested here's an overview as to why__

In the new remapping engine, mouse buttons can have an effect in 2 different ways. As triggers - producing actions directly - or as modifiers - changing what effects other triggers produce. 

For various reasons, whatever actions a button produces as a trigger directly have to be 'oneShot' that is they have to be one and done. The action has to fire at a certain point in time and then be over immediately. This restriction is necessary for things to work properly if you have several actions assigned to a mouse button. This makes it possible to have different actions when clicking, clicking and holding, double clicking, etc.. without those actions interfering.

Now, activating keyboard modifiers _while_ a button is held down doesn't fit into this framework because it's not one and done, it's extended over time. It should start when you press the mouse button and only end when you release it.

However, keyboard shortcuts are currently implemented as such 'oneShot' actions, so we'd have to make a whole new implementation to be able to realise the feature you're asking for.

I haven't thought about this much and there might be a simpler solution, but I think the feature you're asking for would probably best fit into the mechanism mentioned above where mouse buttons can act as modifiers for other triggers. 
The click-and-drag feature works via this mechanism. Here, the mouse-has-moved input is considered the trigger and holding a mouse button modifies the effect of this trigger. 

For the feature you're asking for, you would consider the mouse-is-moved-while-primary-button-is-held  input as the 'trigger' and then have holding another mouse button act as a modifier on this trigger.

But maybe there's a simpler solution I don't see, if anyone has different ideas here, please let me know, I'm very open to any input!

**Comment by DrJume** [comment]
Ok. Thanks for the elaborate explanation!

Yes this flexible trigger and modifier option would be perfect. I could also imagine multiplying the possible mappings when using mouse buttons as modifiers for other mouse buttons, e.g. scroll down while pressing mouse 4; right click while pressing mouse 5. 

For Mosaic it would be sufficient for me, to use the click-and-hold mechanism, to not interfere with other mappings. Because I already use the mouse buttons normal click action for something else. After the delay it would activate the modifier keys(s) and hold it until it is released.

**Comment by noah-nuebling** [comment]
>  I could also imagine multiplying the possible mappings when using mouse buttons as modifiers for other mouse buttons, e.g. scroll down while pressing mouse 4; right click while pressing mouse 5. 

Using mouse buttons as modifiers for other mouse buttons is actually already implemented! Just go to the Add Window and hold a button before pressing another one to start using it.
Using buttons to modify scroll wheel input is not currently supported but the system is built such that that would be relatively easy to implement. I'll definitely try to work on that at some point in the future.

> After the delay it would activate the modifier keys(s) and hold it until it is released.

I understand your idea like this:

__Scenario__ You've mapped some keyboard modifiers to holding a mouse button. \
__Behaviour__ When quickly clicking the button, the modifiers wouldn't be activated. But after you hold the button for a while, then the modifiers would be activated - and stay activated - until the button is released again.
This is in contrast to how it works now, where, after you hold the button for a while, the keyboard shortcut is triggered as a one shot action, more precisely, a keydown and a keyup event are sent immediately, in quick succession without any delay between them. Nothing happens, when the mouse up event occurs.

This is a really interesting idea that I hadn't thought of! I think this could work fairly well for using buttons as keyboard modifiers.

I haven't thought about this much, but off the top of my head I have some concerns when It comes to this:
- There wouldn't be any feedback as to when exactly the modifiers become active, that might be a little confusing and feel weird
- Maybe it would be unintuitive that keyboard shortcuts act differently when assigning them to click-and-hold instead of click triggers
- Also I'm not sure how the UI for recording keyboard modifiers should work. Right now the keyboard shortcut capturing ends when any key that is _not_ a modifier is pressed. We'd need to implement some other way to end capturing keyboard input without pressing a non-modifier-key.

But those are relatively minor problems that I'm sure we could find decent solutions for.

However, implementing this definitely needs a lot of consideration and some changes to how the remapping engine works, and also this is not a top priority for me right now, plus I don't have that much time to work on Mac Mouse Fix, so don't want to promise that I'll implement anything like this soon. 
But this is definitely a really good idea and something I'll keep in mind and think about more.

**Comment by DrJume** [comment]
That's ok! 

Idea for capturing keyboard input in UI: hold down the keyboard shortcut uninterrupted for 1 second, when interrupted or another key is pressed, reset the timer again to 1 second. A simple debounce.

**Comment by noah-nuebling** [comment]
Wow that's a great idea! It seems so obvious now. I didn't know about debouncing that seems like a super useful concept for UI programming. 

I'll almost certainly do it that way if I get around to implementing that feature.

**Comment by noah-nuebling** [comment]
Btw the UI for entering keyboard modifiers on the Scrolling tab in MMF 3 uses your idea. Thanks again :)


https://user-images.githubusercontent.com/40808343/204941627-b672fcda-6680-4374-8071-22352f5bbed3.mov

**Comment by DrJume** [comment]
Wow, that's awesome! 😄 I'm glad I could help!
The pop animation is so satisfying 👍

**Comment by DrJume** [comment]
I can't wait for the final release! There wasn't a Beta released in some time, but it seems that you have been working quite hard according to the commits timeline 😃
