### ISSUE TITLE
activation issue [bug]

### ISSUE THREAD

**Issue by NiaML** [noah-nuebling/Mac-Mouse-Fix#742]
## Description

cant use normally after reboot while in china. Paid and fail to authenticate if i dont have access to the network outside the wall

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: Sonoma
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey man, I'm sorry for the trouble. Does it work if you update to Beta 7?

If you shoot me an email with "Refund" in the subject and share the email you bought the app with I can also refund you.

**Comment by wchjiang28** [comment]
How to buy the software in China？

**Comment by noah-nuebling** [comment]
Hi @wchjiang28, it's currently not possible to buy the app in China because the payment provider Gumroad is blocked in China. I want to add a different payment provider that works in China at some point in the future, but until then, the app is free in China.

There were some bugs with the code for making the app free in China in 3.0.0 Beta 6 and below. But they should be fixed in the latest release. 

If you have any questions or concerns, let me know.

**Comment by wchjiang28** [comment]
That's great! Looking forward to that day. Thank you for your answer

**Comment by cyugao** [comment]
@wchjiang28 
> How to buy the software in China？

If you have Paypal / a credit card that Gumroad accepts. You can
1. Change your region to a country other than China (e.g. United States).
2. Purchase the app.

**Comment by wchjiang28** [comment]
> @wchjiang28
> 
> > How to buy the software in China？
> 
> If you have Paypal / a credit card that Gumroad accepts. You can
> 
> 1. Change your region to a country other than China (e.g. United States).
> 2. Purchase the app.

Thank you for your solution. Currently, I don't have those.
