### ISSUE TITLE
Unable to enable (failed to delete launch.plist) [bug]

### ISSUE THREAD

**Issue by Ivaleraaa** [noah-nuebling/Mac-Mouse-Fix#754]
## Description

Hello !
I have downloaded the app yesterday, and it was working perfectly ! 
But today, it isn't working anymore, and the "Enable mac mouse fix" button won't work
I've read what people asked in other issues, and my problem is still here

I tried to uninstall / reinstall with the download button and via homebrew, and tried to restart my mac, but the problem persists.

Console gives me this error : "Failed to delete launchd.plist file. This might be because the file doesn't exist. If the file still exists at "/Users/[my name]/Library/LaunchAgents/com.nuebling.mac-mouse-fix.helper.plist" the helper might be re-enabled on startup."

I tried to look at the /Users/[my name]/Library/LaunchAgents/ directory, and there is no such file as "com.nuebling.mac-mouse-fix.helper.plist" ? 

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0
macOS Version: Sonoma 14.0
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

Failed to delete launchd.plist file. This might be because the file doesn't exist. If the file still exists at "/Users/[my name]/Library/LaunchAgents/com.nuebling.mac-mouse-fix.helper.plist" the helper might be re-enabled on startup.

**Comment by wakmail** [comment]
Try deleting the app using https://freemacsoft.net/appcleaner/ and restarting the mac. I had an issue similar to yours.

**Comment by Ivaleraaa** [comment]
> Try deleting the app using https://freemacsoft.net/appcleaner/ and restarting the mac. I had an issue similar to yours.

I tried it and it did not work :( 
The console still gives the same error

**Comment by noah-nuebling** [comment]
Hi @Ivaleraaa, thanks for your detailed feedback!

I'm not sure what causes this issue, but I'd really like to fix it. 
There are more troubleshooting steps in issue https://github.com/noah-nuebling/mac-mouse-fix/issues/648. 

If you try the steps there and let me know how it goes that would be super helpful. Thanks!

I'll close this issue now to move all the conversion around the problem to #648.

---

Oh and the ```Failed to delete launchd.plist file. This might be because the file doesn't exist. If the file still exists at "/Users/[my name]/Library/LaunchAgents/com.nuebling.mac-mouse-fix.helper.plist" the helper might be re-enabled on startup.``` message is not an error message even though it says 'failed'. This is perfectly expected and has nothing to do with the issue. It's basically trying to clean up stuff from the old pre-Ventura mechanism for running things in the background. But since you're on Ventura, the `/Users/[your name]/Library/LaunchAgents/com.nuebling.mac-mouse-fix.helper.plist` file is not necessary anymore to run things in the background, therefore it's never created, and that's why it 'fails' to delete the file.
