### ISSUE TITLE
Adding a new button doesn't seem to work - evoluent mouse - also can't close capture window [bug]

### ISSUE THREAD

**Issue by llavalle** [noah-nuebling/mac-mouse-fix#78]
## Description

I'm trying to add an action to button 6 on my mouse... (forward button).   When I hit the   sign, I get the capturezone, click on the button and get erratic behavior.   Most of the time, nothing happens,  Sometimes, a "Double Click button 6" appears, then other times, a "Triple Click button 6".

In all cases, the popup for capture cannot be closed.  Hitting esc or clicking cancel doesn't work.  I need to kill the app.  After a few tries, I can see the "Click Button 6" in the back.  I kill the app then I map the forward button.

The mouse (Evoluent Vertical Mouse 4) has 3 normal buttons   a scrollwheel that can be pressed as well as 2 side buttons.

## Steps to reproduce

1. Start the app
2. Click the plus sign
3. Hit the "forward" button on my mouse (buttonNumber=5 aka Button 6)
4. Sometimes, in the back, get the "click button 6" line added.. sometimes, it's double click, it's weird
5. Get stuck in the capture window

## Context

Mac Mouse Fix Version: 2.0.0 Beta 1
macOS Version: 10.15.7
Mouse Model: Evoluent Vertical Mouse 4

## Additional Comments

–

---

### Console Logs

HID
RECEIVING CG BUTTON INPUT - NSEvent: type=OtherMouseUp loc=(1865,334) time=856.9 flags=0 win=0x0 winNum=0 ctxt=0x0 evNum=59 click=1 buttonNumber=5 pressure=0 deviceID:0x0 subtype=0
PARSING BUTTON INPUT - btn: 6, trigger 1
HANDLING BUTTON TRIGGER - button: 6, triggerType: 1, level: 1, devID: 4294969018
...ON DEVICE - Device Info:
    Model: Evoluent VerticalMouse 4
    VendorID: 6780
    Usage: 2

### Crash Reports

None

**Comment by noah-nuebling** [comment]
Hi @llavvale, thanks for you feedback!

I can't reproduce this issue on my setup, and I have no good idea what might be causing it.

There are 2 things I thought of, but I don't think either is a great explanation.

1. Some gaming mice send double or triple left clicks when pressing certain buttons, so you can shoot faster. But as your mouse doesn't seem to be a gaming mouse, I don't think that's it.
2. I have a mouse with a broken button. When I click it, it's sometimes registered as a double click and sometimes it's not registered at all. This wouldn't explain the Add Window not closing though.

Oh and this might be related:  There was a bug in `Beta 1` where certain users couldn't close the Add Window after opening it, which was fixed in [`Beta 2`](https://github.com/noah-nuebling/mac-mouse-fix/releases). Does using `Beta 2` change anything for your experience?

If anyone can reproduce the problem or has any idea as to why it might be occuring, Your input would be much appreciated!

**Comment by llavalle** [comment]
Sorry - was swamped.  Just upgraded to Beta 3.  Both issues are now fixed.   The Add Window now closes and the double/triple clicks are gone ;)

**Comment by llavalle** [comment]
Closing ;)

**Comment by noah-nuebling** [comment]
Great! Thanks for letting me know :)
