### ISSUE TITLE
Scrolling via mouse wheel fails after switching user profile [bug]

### ISSUE THREAD

**Issue by theronburger** [noah-nuebling/Mac-Mouse-Fix#789]
## Description

Hi there. Love the product! 
When switching users  scrolling stops working. I need to disable and re-enable mac mouse fix to get it working. 

## Steps to reproduce

Set up Mac Mouse Fix on two user profiles on one mac running Sonoma (14.1.1)
Switch users
Scrolling via mouse wheel fails. Touchpad scrolling still works. 
toggle enable
scrolling works again

## Context

Mac Mouse Fix Version: 3.0.0
macOS Version: Sonoma 14.1.1
Mouse Model: MX Anywhere 3

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi, thanks for reaching out!

Theres a workaround for this problem: Log **out** of the current user before switching to a new user.

I put off trying to fix this, because I planned to rewrite some internal systems to add support for some mice like the MX Master and that rewrite would also fix this issue. 

But since a lot of people are complaining about this, I’ll try to build some temporary solution before the bigger rewrite. I don’t want to make promises, but I hope I can release that soon.

**Comment by noah-nuebling** [comment]
Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.

**Comment by theronburger** [comment]
So fast! Amazing, will give it a spin

**Comment by noah-nuebling** [comment]
Yeah it was a lot faster than I anticipated! Some of the optimization code in MMF 3 made it pretty straight-forward to implement. Let me know if there's any issues.
