### ISSUE TITLE
Add an option to disable `Click and Drag` when triggering `Click and Scroll` [enhancement]

### ISSUE THREAD

**Issue by zzzchuu** [noah-nuebling/Mac-Mouse-Fix#793]
## Description
When action `Click and Scroll` is happening and the button is still not released, block the `Click and Drag` action.

## Rationale
When Im doing `Click and Scroll`, my hand moves easily and it is recognized as `Click and Drag`, especially when using Middle Click's `Click and Scroll`.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey there @edr1412, thanks for your feedback! 

I'm not sure I would like to implement what you suggest.

Here are the 2 points that make me doubtful:

1. Sometimes, it's a really nice feature to be able to combine Click and Drag with Click and Scroll and use them both at the same time. (For example when using "Scroll & Navigate" together with "Zoom In or Out")
2. I think using Click and Scroll on the Middle Button (aka the Scrollwheel Button) will inevitable be a finicky and suboptimal experience, even if your suggestion was implemented. Because of this, I also plan to remove the "Click and Scroll" Gesture on the "Middle Button" from the default settings.

The default settings for mice with 3 buttons will probably look like this in the future:

<img width="556" alt="Screenshot 2024-01-15 at 22 34 52" src="https://github.com/noah-nuebling/mac-mouse-fix/assets/40808343/0c85ac05-8df3-4e64-bd34-c05be81c1c16">

However, there are definitely cases where it doesn't make sense to combine certain Click and Scroll Gestures with certain Click and Drag Gestures, and in those cases, the app should probably make a deliberate decision to either cancel the first gesture in favor of the second gesture, or to 'lock into' the first gesture and ignore the second gesture.

So I agree that this variation of your suggestion should probably be implemented, but I'm not sure how hard this would be and it's not a super high priority as of now, since I don't think the current behaviour leads to significant usability issues. My assessment on the usability impact is because I assume that your problems with using Click and Scroll on the Middle Button wouldn't really be fixed by implementing your suggestion, and you would still find it difficult and finicky to use, because it's just physically difficult to do.


I hope this was somewhat understandable (I'm kinda tired) and if you disagree with any of my assessments, or you have any more ideas or suggestions, please let me know.

**Comment by rabomen** [comment]
@noah-nuebling  Certainly, I completely understand. I think my mouse's middle button is  particularly physically stiff, which might not be a significant issue for others.
