### ISSUE TITLE
Stop messing around with the scrolling behavior, or else I will get a refund. [bug]

### ISSUE THREAD

**Issue by programadorbt4** [noah-nuebling/mac-mouse-fix#872]
## Description

Stop messing around with the scrolling behavior, or else I will get a refund.

> In 3.0.2 the speedup of the animation should appear more consistent and predictable, making it easier on the eyes while providing great control.

I want to revert back to the original scrolling from 3.0.1, because it bothers me. It literary cost me get used to from 2.0 to 3.0 and now, I have to deal with this.

Dealing with these small things, makes me **break my muscle memory** every time there's an update.

Sorry for any english mistake.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: 14.3.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hello @programadorbt4, I'm sorry for the frustration. I'm doing my best to make the experience as good as possible for everyone, and I will keep iterating on the existing behaviour in order to improve the experience.

There is no refund policy, but if you send me the email address you've bought the app with, I will give you a refund.

If you let me know what exactly about the scrolling behaviour from 3.0.1 you prefer, I will take that into account.
