### ISSUE TITLE
Each update, my muscle memory gets corrupted [bug]

### ISSUE THREAD

**Issue by programadorbt4** [noah-nuebling/Mac-Mouse-Fix#873]
## Description

The original issue (which get deleted) I clearly expressed that everytime I update Mac Mouse Fix, there's always something that clearly bothers me, and makes my muscle memory break.

This problem was mainly noticed from version 2.0 to version 3.

> Improved on a mechanism introduced in 3.0.1 where the animation speed becomes faster as you move the scroll wheel faster when using 'Smoothness: Regular'

I am now seeing it again from version 3.0.1 to version 3.0.2.
This overall, makes me not trust each update, because it's going to destroy my overall experience of the product.

Can this be addressed? (and not deleted again?)

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: 14.3.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there @programadorbt4, thanks for your feedback. I understand your concerns. I deleted your original issue, because I felt like you were threatening me and it made me anxious.

However, I do understand this concern. Going forward, I plan to not ship changes that are relatively fundamental to the way you use Mac Mouse Fix in point updates such as 3.0.2. 

If I do ship any such changes, I will clearly mark this in the update notes. 

I hope this works for you.

If you would like a refund, shoot me an email, including the email address you bought Mac Mouse Fix with.

Thank you.
