### ISSUE TITLE
Smooth scrolling for horizontal wheel [enhancement]

### ISSUE THREAD

**Issue by t-millot** [noah-nuebling/mac-mouse-fix#91]
## Description
It would be really nice if you could apply the same smooth scrolling algorithm to the horizontal scrolling as well (for mouse that support this function).

## Rationale
Right now this is a bit choppy compared to the main scroll, and apps like MOS and SmoothScroll already apply their profile to horizontal scroll.

**Comment by noah-nuebling** [comment]
Hi Tom thanks for your feedback!

The app should normally do that. I've experienced the same issue that you describe when using Swish.app along with Mac Mouse Fix. Do you think Swish or some other software that you're running might be causing these issues?

I'll look into fixing the issue with Swish soon, but I don't know what the cause is at this point so I don't want to promise anything.

If you find out anything else regarding the issue lt me know! I'd love to see this resolved, too, and any clue as to what is causing it would be super helpful.

**Comment by noah-nuebling** [comment]
Oh I misunderstood you, sorry. You're right, horizontal scroll input is currently ignored by Mac Mouse Fix.
I'd love to build a system where you can write plug-ins to support mouse-specific features at some point, and I think proper support for tilt-wheels and horizontal wheels is a prime candidate to focus on for such a plug-in.
Then you could maybe even adjust the speed of the horizontal scrolling or even remap it to different functions like moving between Spaces, or Back and Forward.
I want to focus on different improvements to Mac Mouse Fix first, so please don't expect anything in this regard any time soon.

The current system is very much built around supporting standard, vertical scroll-wheels, and to support horizontal scroll inputs would take quite a bit of consideration and refactoring. A lot of this work might be in vain, when we build the proper mouse-support plug-in, though so I think it's wiser to wait with the implementation of that.

That's my thinking on it anyways, which might be flawed.

If you have any more thoughts or questions, or disagree with anything, let me know!

**Comment by t-millot** [comment]
Hi, thank you for your thorough response. I understand why it is not implemented yet (as a developper myself, I know this kind of stuff is not trivial). The idea of a plugin system sounds very interesting, I'd love to see what it could become.
I think your app has the potential to become a standard modern mouse driver for the Mac, potentially entirely replacing crapy first party mouse software (at the cost of some niche features). It's so close already for me with beta 2.0 to replace Logitech Option for Mx Master mouse. The only thing holding me back right now is the horizontal scrolling kind of broken without official software.

Keep up the good work, it's really appreciated (I would mind paying for your app, it's worth it).

**Comment by noah-nuebling** [comment]
Wow thanks for your praise and for elaborating on your thoughts Tom!

Below are some of my plans for the future of Mac Mouse Fix.
I wasn't sure if they are interesting or relevant to you, but I wrote them out anyways because I thought they might be interesting and it really helps me wrap my head around things to try and explain them. 
If you don't have time to look at them, just ignore them. It's totally fine and I 100% get it.


**Roadmap**

My current plan for the app looks something like this:

First I'll work on the core features and user experience so it's really good and attractive and everyone can see the potential. I'd then implement some nice way to monetise the app, so that I can spend more time on it in the future. After that, I'll do a little bit of marketing, so the app gets as much attention as possible.
Then, if the app gains traction, I'll try to make it a complete package, by making it fully compatible with as many mice as possible through a device-support plug-in system. This should bring full support for horizontal scroll wheels like on your MX Master. Hopefully I'll be able to encourage others to write plug-ins as well, because it's not practical to do that all by myself. There are just way too many models of mice.

Then finally, I'd add more somewhat-niche and hard to implement features that would make it a complete package for almost everyone. E.g. full app-specific overrides and the ability to change pointer sensitivity.

All of this isn't super easy to do and takes a lot of thought and time, so we'll see how goes but that's the plan. I have a lot of free time this summer and I'm really excited to make Mac Mouse Fix even more awesome! :)

**Monetization**

When it comes to monetization, I'm not sure how to do it, yet. But here are some ideas:

1. Making it completely optional, but encouraging it in nice, unobtrusive ways.
We would keep everything completely free, but then, when downloading the app, you'd have a popup say something like "Hey I'm Noah and I made this app. If you like it, consider buying it. I'd really appreciate it and it allows me to spend time making the app even better. But if you don't want to, that's perfectly fine as well. You can just download it for free and the free version will work exactly the same as the paid version." 
And then maybe you'd have some cute button in the app on the About page which displays whether you've payed for the app or not, to remind people in a subtle way and to make it a little satisfying to pay for the app.
I like this because it doesn't force you to pay to get any benefits or features you might need. I think people will feel much better about choosing to pay for the app because they think it deserves it and to support it rather than being forced to.
2. Locking some "advanced" features behind a paywall. 
While it would allow people to easily test out the app, and then provide a pretty strong incentive to pay, I don't like it emotionally. I don't like being teased with stuff in an app that I could do but can't because I have the 'incomplete version'. There being an 'incomplete version' at all diminishes the perceived value and quality of the app to me I think.
3. Trial version. 
This is similar to the paywall but a bit better. Emotionally, a limited-time test of the complete version feels much better to me than having an 'incomplete version'. Also, the incentive to pay is probably a little higher. 
Maybe I could make things nicer by implementing a system where the trial countdown only ticks down on days on which you actually use the app. That's something that sometimes annoys me about other trial versions of software - I'll test them out for a day, then forget about them for a month, and then the trial is over.
4. Making the app only downloadable when you pay for it. 
I feel like I can't do that because we're never sure if the app is even compatible with a users mouse beforehand. We don't want them to pay for the app and then discover that it doesn't even work for them. Also this would greatly diminish the number of people that would even try it out - I feel like this is made even worse since the app isn't on the App Store. I sometimes buy apps with an up-front cost on the App Store, but I never have done so with an app from the internet I think.

So I think I'll try strategy 1. first and if that doesn't turn out to be sustainable I'll do a trial version instead.
Wow, writing that just made me come to this conclusion, awesome!

What are your thoughts on this? Is there any specific pricing model that you'd prefer?
If you have any thoughts or feedback on anything else, I'd love to hear that, too of course! None if this is set in stone and I'm always looking for different ideas.

**Comment by gagarine** [comment]
I just acquired a Logitech MX master 3 and after an hours was on the verge of returning the mouse because of their incredibly crap driver and configuration software. In particular they use way too much CPU for a simple mouse driver. You save my day (even if some feature are missing, my mouse is usable)!

@noah-nuebling In term of monetising, I would be happy to pay about 5$ if the code stay open source. I do not like when advanced feature is for pay because it feel like a lock-in. Definitely trial is needed.

An alternative to trial would be to make automatic update a pay feature. I would pay 5$ for that convenience too.

Now, 5$ I would pay without even thinking about it. More than 10$ I will start to look for alternative, certainly lose time, and then probable pay for it. More than 20$, I will use Logitech crap :/.

**Comment by noah-nuebling** [comment]
Hello @Tom1206, in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases) the scroll smoothing is also applied to horizontal scroll input from your mouse!

I'd still like to write some custom handling code for tilt wheels at some point so that things feel even better. But I think the way that things are is already much better than before.

@gagarine, really happy to hear you like the app and thanks for your input on monetization! MMF 3 will cost $1.99 and it will have a trial period which only counts days where you actually use the app! It's also still open source! So I hope you'll be happy with that! 

Let me know if you have more thoughts or questions!
