### ISSUE TITLE
MMF Keeps Crashing while scrolling in Chrome [bug]

### ISSUE THREAD

**Issue by mhtawfiq** [noah-nuebling/Mac-Mouse-Fix#914]
## Description

Crash Report attached

## Steps to reproduce

Scroll a long website in Chrome, MMF keeps crashing and reloading.

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: 14.4.1
Mouse Model: Logitech MX Master 3

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

https://pastebin.com/PGg0uban

**Comment by noah-nuebling** [comment]
Hey there, thanks for your report! 

This should be fixed in the latest [3.0.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.3). 

If you're still experiencing these crashes (or if you did still experience them when you were last using 3.0.2) it would be really valuable if you sent your config.plist file so I can have a look at it.

The config.plist file holds pretty much all settings and state that is retained between launches of the app. You can find it like this:

1. Open Mac Mouse Fix
2. Go to the 'About' tab
3. Click the Mac Mouse Fix Icon while holding Command (⌘) and Shift (⇧). This should reveal the 'config.plist' file in the Finder.

I'm closing this Issue now, so everything related to this bug is in one place. For further discussion and details, please use Issue [#988](https://github.com/noah-nuebling/mac-mouse-fix/issues/988#issuecomment-2359171135). Thank you.
