### ISSUE TITLE
Mac Mouse Fix keeps crashing randomly when scrolling [bug]

### ISSUE THREAD

**Issue by chris-moon** [noah-nuebling/Mac-Mouse-Fix#925]
## Description

It'll be working and then suddenly my scrolling becomes erratic. The app icon disappears from the menu bar and comes back again after a few seconds.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: 14.4.1 (23E224)
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by lsh411** [comment]
same here

**Comment by Lx** [comment]
Me too:
- macOS Version 14.5 (23F79)
- Mac Mouse Fix Version 3.0.2 (22635).

Please let me know if I can provide anything of further use, e.g., log files.

**Comment by dorkyboi** [comment]
Same over here.
Mac mouse fix: Version 3.0.2 (22635)
macbook m2 pro with Sonoma 14.6.1

In my experience, it seems to crash when scrolling too quickly, or back and forth

UPD: seems to be crashing only in specific apps - for me, it's scrolling through project structure tree in VS Code

**Comment by noah-nuebling** [comment]
Hey guys, thanks for the bug report.

This should be fixed in the latest [3.0.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.3). 

If anybody's still experiencing these crashes (or if you did still experience them when you were last using 3.0.2) it would be really valuable if you sent your config.plist file so I can have a look at it.

The config.plist file holds pretty much all settings and state that is retained between launches of the app. You can find it like this:

1. Open Mac Mouse Fix
2. Go to the 'About' tab
3. Click the Mac Mouse Fix Icon while holding Command (⌘) and Shift (⇧). This should reveal the 'config.plist' file in the Finder.

I'm closing this Issue now, so everything related to this bug is in one place. For further discussion and details, please use Issue [#988](https://github.com/noah-nuebling/mac-mouse-fix/issues/988#issuecomment-2359171135). Thank you.
