### ISSUE TITLE
MMF scrolling only works with one user profile [bug]

### ISSUE THREAD

**Issue by gaterose** [noah-nuebling/mac-mouse-fix#93]
## Description

MMF scrolling will only work on one user profile. Tried with multiple input devices.

I originally installed MMF on my profile and have used it for almost a year. Found out over the weekend that the scroll wheel has never worked in my wife's user account so I deleted the app from her applications. I reinstalled MMF and it worked fine for her.

Today I logged back into my account and realized now scrolling doesn't work for me. Tried reinstalling MMF to no avail. Changing the side buttons from back/forward to spaces works fine but nothing will enable scrolling.

It may be worth mentioning that when MMF was a preference (instead of app) I would have to disable and re-enable MMF after every time she used the computer.

## Steps to reproduce

Have multiple user accounts
Install MMF on one account

## Context

Mac Mouse Fix Version: 2.0.0 Beta 5
macOS Version: 10.15.7
Mouse Model: logitech g502 (wired), Dell KM7321W (wireless), Logitech DiNovo Edge (wireless)

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @gaterose, thank you for reaching out!

It's very valuable that you did, because I wasn't aware of this issue until now.

I've made some changes in [2.0.0 Beta 6](https://github.com/noah-nuebling/mac-mouse-fix/releases) that should fix or at least improve things for you.
Let me know how that works for you guys.

**Comment by gaterose** [comment]
Wow, thanks for the fast reply Noah! That seems to have fixed the scroll wheel, but now button 4 & 5 are left clicking instead of going back and forward as set in her profile. I tried some other functions, but it left-clicks no matter what. 4 & 5 seem to work right in my profile (the user account where I installed the app).

As mentioned above, in the previous version I was using (1.0.5 I think? whatever is on the website) 4 and 5 did work properly in both profiles even though scrolling didn't.

**Comment by noah-nuebling** [comment]
Hey @gaterose, sorry for the late reply. 

In the mean time there was a little meltdown where no one in the whole wide world could open the app anymore. But fortunately that's now tended to.

The quick fix to your problem I made in Beta 6 turned out to introduce many more issues than it alleviated. 
I've thought about the underlying issue deeply and I discovered that I need to make big changes in the app to fix it properly without breaking a whole bunch of other stuff.
I've decided that it's not smart for me to implement these huge changes at this point in development. Sorry for that.

I have however made some changes in [2.0.0 Beta 9](https://github.com/noah-nuebling/mac-mouse-fix/releases) that should make the app just as usable as the older 1.0 version you were using. 
With Beta 9, after switching to a new account, simply turn Mac Mouse Fix off and on again to get things working. 

If Mac Mouse Fix is running in one user session but not the other, scrolling will still not work in the user session which doesn't have Mac Mouse Fix running. To prevent these issues entirely, you could also log out before logging into a different user account.

Hope this helps, and if you have any more questions or issues you know the drill.

**Comment by MattKleinsmith** [comment]
Disabling and re-enabling Mac Mouse Fix has been my (inconvenient) workaround:

![CleanShot 2023-03-10 at 20 35 33](https://user-images.githubusercontent.com/8968171/224460577-9d1f97b5-0723-4ec7-859e-fe0a9d755b26.gif)

Does anyone have an idea on how to automate this? I'm new to Mac. Maybe there's a user switch OS hook, where we could run a script that could kill Mac Mouse Fix and then start it again. Will post here if I figure it out.

Edit:

[UserSwitchNotifications](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPMultipleUsers/Concepts/UserSwitchNotifications.html#//apple_ref/doc/uid/20002210-CJBJDAGF) might be helpful.

**Comment by muzzakus** [comment]
What a wonderful extension to the abysmal Apple support of 3rd party mice.  However the lack of proper function for multiple accounts is a real bummer.  Hope improvements can be made to an already stellar piece of software!

**Comment by noah-nuebling** [comment]
Hey guys, I finally fixed this in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.

**Comment by noah-nuebling** [comment]
Thanks @muzzakus for letting me know you like the app!
